import path from 'path';
import { mkdirSync, existsSync, writeFileSync } from 'fs';
import { Logger } from '../../utils/Logger.js';

/**
 * Generate language config file for scripts
 */
export class LanguageConfigBPGenerator {
  /**
   * Generate GeneratedLanguage.ts
   */
  static async generate(language: string, outputDir: string): Promise<void> {
    // Output to root scripts/data folder (for TypeScript compilation)
    const scriptsDataDir = path.join(outputDir, '..', '..', 'scripts', 'data');
    
    // Create directory if not exists
    if (!existsSync(scriptsDataDir)) {
      mkdirSync(scriptsDataDir, { recursive: true });
    }

    const content = `/**
 * Generated Language Config
 * DO NOT EDIT - Auto-generated by addon-generator
 * 
 * This file is generated from addon.yaml language setting
 */

export const GENERATED_LANGUAGE = '${language}';
`;

    const filePath = path.join(scriptsDataDir, 'GeneratedLanguage.ts');
    writeFileSync(filePath, content, 'utf-8');
    
    Logger.log(`✅ Đã tạo: scripts/data/GeneratedLanguage.ts (language: ${language})`);
  }
}
