/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by addon-generator CLI
 * 
 * Để thêm/sửa/xóa content:
 * 1. Edit YAML files trong addon-generator/configs/
 * 2. Run: bun run dev compile configs/addon.yaml
 * 3. File này sẽ được regenerate tự động
 */

/**
 * Generated ore data
 */
export const GENERATED_ORES = [
  {
    blockId: "apeirix:tin_ore",
    dropItem: "apeirix:raw_tin",
    dropCount: 1,
    fortuneEnabled: true
  },
  {
    blockId: "apeirix:deepslate_tin_ore",
    dropItem: "apeirix:raw_tin",
    dropCount: 1,
    fortuneEnabled: true
  },
  {
    blockId: "apeirix:silver_ore",
    dropItem: "apeirix:raw_silver",
    dropCount: 1,
    fortuneEnabled: true
  },
  {
    blockId: "apeirix:deepslate_silver_ore",
    dropItem: "apeirix:raw_silver",
    dropCount: 1,
    fortuneEnabled: true
  },
  {
    blockId: "apeirix:nickel_ore",
    dropItem: "apeirix:raw_nickel",
    dropCount: 1,
    fortuneEnabled: true
  },
  {
    blockId: "apeirix:deepslate_nickel_ore",
    dropItem: "apeirix:raw_nickel",
    dropCount: 1,
    fortuneEnabled: true
  },
  {
    blockId: "apeirix:lead_ore",
    dropItem: "apeirix:raw_lead",
    dropCount: 1,
    fortuneEnabled: true
  },
  {
    blockId: "apeirix:deepslate_lead_ore",
    dropItem: "apeirix:raw_lead",
    dropCount: 1,
    fortuneEnabled: true
  },
  {
    blockId: "apeirix:platinum_ore",
    dropItem: "apeirix:raw_platinum",
    dropCount: 1,
    fortuneEnabled: true
  },
  {
    blockId: "apeirix:deepslate_platinum_ore",
    dropItem: "apeirix:raw_platinum",
    dropCount: 1,
    fortuneEnabled: true
  },
  {
    blockId: "apeirix:cobalt_ore",
    dropItem: "apeirix:raw_cobalt",
    dropCount: 1,
    fortuneEnabled: true
  },
  {
    blockId: "apeirix:deepslate_cobalt_ore",
    dropItem: "apeirix:raw_cobalt",
    dropCount: 1,
    fortuneEnabled: true
  },
  {
    blockId: "apeirix:ardite_ore",
    dropItem: "apeirix:raw_ardite",
    dropCount: 1,
    fortuneEnabled: true
  },
  {
    blockId: "apeirix:deepslate_ardite_ore",
    dropItem: "apeirix:raw_ardite",
    dropCount: 1,
    fortuneEnabled: true
  }
];

/**
 * Generated tool data
 */
export const GENERATED_TOOLS = [
  {
    id: "apeirix:bronze_pickaxe",
    type: "pickaxe" as const,
    durability: 375
  },
  {
    id: "apeirix:bronze_axe",
    type: "axe" as const,
    durability: 375
  },
  {
    id: "apeirix:bronze_shovel",
    type: "shovel" as const,
    durability: 375
  },
  {
    id: "apeirix:bronze_hoe",
    type: "hoe" as const,
    durability: 375
  },
  {
    id: "apeirix:bronze_sword",
    type: "sword" as const,
    durability: 375
  },
  {
    id: "apeirix:bronze_spear",
    type: "spear" as const,
    durability: 375
  },
  {
    id: "apeirix:steel_alloy_pickaxe",
    type: "pickaxe" as const,
    durability: 750
  },
  {
    id: "apeirix:steel_alloy_axe",
    type: "axe" as const,
    durability: 750
  },
  {
    id: "apeirix:steel_alloy_shovel",
    type: "shovel" as const,
    durability: 750
  },
  {
    id: "apeirix:steel_alloy_hoe",
    type: "hoe" as const,
    durability: 750
  },
  {
    id: "apeirix:steel_alloy_sword",
    type: "sword" as const,
    durability: 750
  },
  {
    id: "apeirix:silver_pickaxe",
    type: "pickaxe" as const,
    durability: 375
  },
  {
    id: "apeirix:silver_axe",
    type: "axe" as const,
    durability: 375
  },
  {
    id: "apeirix:silver_shovel",
    type: "shovel" as const,
    durability: 375
  },
  {
    id: "apeirix:silver_hoe",
    type: "hoe" as const,
    durability: 375
  },
  {
    id: "apeirix:silver_sword",
    type: "sword" as const,
    durability: 375
  },
  {
    id: "apeirix:silver_hammer",
    type: "hammer" as const,
    durability: 375
  },
  {
    id: "apeirix:nickel_pickaxe",
    type: "pickaxe" as const,
    durability: 450
  },
  {
    id: "apeirix:nickel_axe",
    type: "axe" as const,
    durability: 450
  },
  {
    id: "apeirix:nickel_shovel",
    type: "shovel" as const,
    durability: 450
  },
  {
    id: "apeirix:nickel_hoe",
    type: "hoe" as const,
    durability: 450
  },
  {
    id: "apeirix:nickel_sword",
    type: "sword" as const,
    durability: 450
  },
  {
    id: "apeirix:nickel_hammer",
    type: "hammer" as const,
    durability: 675
  },
  {
    id: "apeirix:lead_pickaxe",
    type: "pickaxe" as const,
    durability: 400
  },
  {
    id: "apeirix:lead_axe",
    type: "axe" as const,
    durability: 400
  },
  {
    id: "apeirix:lead_shovel",
    type: "shovel" as const,
    durability: 400
  },
  {
    id: "apeirix:lead_hoe",
    type: "hoe" as const,
    durability: 400
  },
  {
    id: "apeirix:lead_sword",
    type: "sword" as const,
    durability: 400
  },
  {
    id: "apeirix:lead_hammer",
    type: "hammer" as const,
    durability: 600
  },
  {
    id: "apeirix:electrum_pickaxe",
    type: "pickaxe" as const,
    durability: 425
  },
  {
    id: "apeirix:electrum_axe",
    type: "axe" as const,
    durability: 425
  },
  {
    id: "apeirix:electrum_shovel",
    type: "shovel" as const,
    durability: 425
  },
  {
    id: "apeirix:electrum_hoe",
    type: "hoe" as const,
    durability: 425
  },
  {
    id: "apeirix:electrum_sword",
    type: "sword" as const,
    durability: 425
  },
  {
    id: "apeirix:electrum_hammer",
    type: "hammer" as const,
    durability: 640
  },
  {
    id: "apeirix:invar_pickaxe",
    type: "pickaxe" as const,
    durability: 500
  },
  {
    id: "apeirix:invar_axe",
    type: "axe" as const,
    durability: 500
  },
  {
    id: "apeirix:invar_shovel",
    type: "shovel" as const,
    durability: 500
  },
  {
    id: "apeirix:invar_hoe",
    type: "hoe" as const,
    durability: 500
  },
  {
    id: "apeirix:invar_sword",
    type: "sword" as const,
    durability: 500
  },
  {
    id: "apeirix:invar_hammer",
    type: "hammer" as const,
    durability: 750
  },
  {
    id: "apeirix:platinum_pickaxe",
    type: "pickaxe" as const,
    durability: 1600
  },
  {
    id: "apeirix:platinum_axe",
    type: "axe" as const,
    durability: 1600
  },
  {
    id: "apeirix:platinum_shovel",
    type: "shovel" as const,
    durability: 1600
  },
  {
    id: "apeirix:platinum_hoe",
    type: "hoe" as const,
    durability: 1600
  },
  {
    id: "apeirix:platinum_sword",
    type: "sword" as const,
    durability: 1600
  },
  {
    id: "apeirix:platinum_hammer",
    type: "hammer" as const,
    durability: 2400
  },
  {
    id: "apeirix:tin_pickaxe",
    type: "pickaxe" as const,
    durability: 375
  },
  {
    id: "apeirix:tin_axe",
    type: "axe" as const,
    durability: 375
  },
  {
    id: "apeirix:tin_shovel",
    type: "shovel" as const,
    durability: 375
  },
  {
    id: "apeirix:tin_hoe",
    type: "hoe" as const,
    durability: 375
  },
  {
    id: "apeirix:tin_sword",
    type: "sword" as const,
    durability: 375
  },
  {
    id: "apeirix:tin_hammer",
    type: "hammer" as const,
    durability: 562
  },
  {
    id: "apeirix:cobalt_pickaxe",
    type: "pickaxe" as const,
    durability: 500
  },
  {
    id: "apeirix:cobalt_axe",
    type: "axe" as const,
    durability: 500
  },
  {
    id: "apeirix:cobalt_shovel",
    type: "shovel" as const,
    durability: 500
  },
  {
    id: "apeirix:cobalt_hoe",
    type: "hoe" as const,
    durability: 500
  },
  {
    id: "apeirix:cobalt_sword",
    type: "sword" as const,
    durability: 500
  },
  {
    id: "apeirix:cobalt_hammer",
    type: "hammer" as const,
    durability: 750
  },
  {
    id: "apeirix:ardite_pickaxe",
    type: "pickaxe" as const,
    durability: 500
  },
  {
    id: "apeirix:ardite_axe",
    type: "axe" as const,
    durability: 500
  },
  {
    id: "apeirix:ardite_shovel",
    type: "shovel" as const,
    durability: 500
  },
  {
    id: "apeirix:ardite_hoe",
    type: "hoe" as const,
    durability: 500
  },
  {
    id: "apeirix:ardite_sword",
    type: "sword" as const,
    durability: 500
  },
  {
    id: "apeirix:ardite_hammer",
    type: "hammer" as const,
    durability: 750
  },
  {
    id: "apeirix:manyullyn_pickaxe",
    type: "pickaxe" as const,
    durability: 800
  },
  {
    id: "apeirix:manyullyn_axe",
    type: "axe" as const,
    durability: 800
  },
  {
    id: "apeirix:manyullyn_shovel",
    type: "shovel" as const,
    durability: 800
  },
  {
    id: "apeirix:manyullyn_hoe",
    type: "hoe" as const,
    durability: 800
  },
  {
    id: "apeirix:manyullyn_sword",
    type: "sword" as const,
    durability: 800
  },
  {
    id: "apeirix:manyullyn_hammer",
    type: "hammer" as const,
    durability: 1200
  },
  {
    id: "apeirix:wooden_hammer",
    type: "hammer" as const,
    durability: 59
  },
  {
    id: "apeirix:stone_hammer",
    type: "hammer" as const,
    durability: 131
  },
  {
    id: "apeirix:copper_hammer",
    type: "hammer" as const,
    durability: 200
  },
  {
    id: "apeirix:iron_hammer",
    type: "hammer" as const,
    durability: 250
  },
  {
    id: "apeirix:golden_hammer",
    type: "hammer" as const,
    durability: 32
  },
  {
    id: "apeirix:bronze_hammer",
    type: "hammer" as const,
    durability: 375
  },
  {
    id: "apeirix:steel_alloy_hammer",
    type: "hammer" as const,
    durability: 750
  },
  {
    id: "apeirix:diamond_hammer",
    type: "hammer" as const,
    durability: 1561
  },
  {
    id: "apeirix:netherite_hammer",
    type: "hammer" as const,
    durability: 2031
  }
];

/**
 * Generated food data
 */
export const GENERATED_FOODS = [
  {
    itemId: "apeirix:canned_pumpkin",
    effects: [
      { name: "fire_resistance", duration: 15 * 20, amplifier: 0, chance: 1 }
    ],
  },
  {
    itemId: "apeirix:cannedcarrots",
    effects: [
      { name: "night_vision", duration: 15 * 20, amplifier: 0, chance: 1 }
    ],
  },
  {
    itemId: "apeirix:canneddogfood",
    effects: [
      { name: "nausea", duration: 10 * 20, amplifier: 0, chance: 1 }
    ],
  },
  {
    itemId: "apeirix:cannedfish",
    effects: [
      { name: "water_breathing", duration: 30 * 20, amplifier: 0, chance: 1 }
    ],
  },
  {
    itemId: "apeirix:cannedmeal",
    effects: [
      { name: "regeneration", duration: 3 * 20, amplifier: 0, chance: 1 }
    ],
  },
  {
    itemId: "apeirix:cannedsalad",
    effects: [
      { name: "health_boost", duration: 10 * 20, amplifier: 0, chance: 1 }
    ],
  },
  {
    itemId: "apeirix:luncheonmeat",
    effects: [
      { name: "saturation", duration: 1 * 20, amplifier: 0, chance: 1 }
    ],
  },
  {
    itemId: "apeirix:fruit_salad",
    effects: [
      { name: "speed", duration: 20 * 20, amplifier: 0, chance: 1 }
    ],
  },
  {
    itemId: "apeirix:chickensoup",
    effects: [
      { name: "regeneration", duration: 10 * 20, amplifier: 0, chance: 1 }
    ],
  },
  {
    itemId: "apeirix:cookies",
    effects: [
      { name: "haste", duration: 15 * 20, amplifier: 0, chance: 1 }
    ],
  }
];

/**
 * Generated wiki item data
 */
export const GENERATED_WIKI_ITEMS = [
  {
    id: "apeirix:raw_tin",
    category: "materials",
    name: "Thiếc Thô",
    icon: "textures/items/raw_tin",
  },
  {
    id: "apeirix:tin_ingot",
    category: "materials",
    name: "Thỏi Thiếc",
    icon: "textures/items/tin_ingot",
  },
  {
    id: "apeirix:tin_nugget",
    category: "materials",
    name: "Mảnh Thiếc",
    icon: "textures/items/tin_nugget",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:tin_block",
    category: "materials",
    name: "Khối Thiếc",
  },
  {
    id: "apeirix:tin_ore",
    category: "materials",
    name: "Quặng Thiếc",
  },
  {
    id: "apeirix:bronze_ingot",
    category: "materials",
    name: "Thỏi Đồng Thanh",
    description: "Hợp kim đồng thanh được tạo từ đồng (copper) và thiếc. Bền hơn đồng nguyên chất, dùng để chế tạo công cụ và giáp.",
    icon: "textures/items/bronze_ingot",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:bronze_nugget",
    category: "materials",
    name: "Mảnh Đồng Thanh",
    icon: "textures/items/bronze_nugget",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:bronze_ingot_dust",
    category: "materials",
    name: "Bụi Đồng Thanh",
    icon: "textures/items/bronze_ingot_dust",
    info: {
      "Chế tạo": "4 nguyên liệu"
    },
  },
  {
    id: "apeirix:bronze_ingot_dust_pure",
    category: "materials",
    name: "Bụi Đồng Thanh Tinh Khiết",
    icon: "textures/items/bronze_ingot_dust_pure",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:raw_bronze",
    category: "materials",
    name: "Đồng Thanh Thô",
    icon: "textures/items/raw_bronze",
  },
  {
    id: "apeirix:bronze_block",
    category: "materials",
    name: "Khối Đồng Thanh",
  },
  {
    id: "apeirix:alloy_mixing_table",
    category: "materials",
    name: "alloy_mixing_table",
  },
  {
    id: "apeirix:steel_alloy_ingot",
    category: "materials",
    name: "Thỏi Hợp Kim Thép",
    icon: "textures/steel_alloy/steel_alloy_ingot",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:steel_alloy_nugget",
    category: "materials",
    name: "Mảnh Hợp Kim Thép",
    icon: "textures/steel_alloy/steel_alloy_nugget",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:steel_alloy_dust",
    category: "materials",
    name: "Bụi Hợp Kim Thép",
    icon: "textures/steel_alloy/steel_alloy_dust",
    info: {
      "Chế tạo": "4 nguyên liệu"
    },
  },
  {
    id: "apeirix:steel_alloy_dust_pure",
    category: "materials",
    name: "Bụi Hợp Kim Thép Tinh Khiết",
    icon: "textures/steel_alloy/steel_alloy_dust_pure",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:raw_steel",
    category: "materials",
    name: "Hợp Kim Thép Thô",
    icon: "textures/items/raw_steel",
  },
  {
    id: "apeirix:steel_alloy_base_plate",
    category: "materials",
    name: "Tấm Thép",
    icon: "textures/steel_alloy/steel_alloy_base_plate",
  },
  {
    id: "apeirix:steel_alloy_base_rod",
    category: "materials",
    name: "Thanh Thép",
    icon: "textures/steel_alloy/steel_alloy_base_rod",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:steel_alloy_base_gear",
    category: "materials",
    name: "Bánh Răng Thép",
    icon: "textures/steel_alloy/steel_alloy_base_gear",
    info: {
      "Chế tạo": "2 nguyên liệu"
    },
  },
  {
    id: "apeirix:engineering_hammer",
    category: "materials",
    name: "Búa Kỹ Thuật",
    icon: "textures/steel_alloy/engineering_hammer",
    info: {
      "Chế tạo": "2 nguyên liệu"
    },
  },
  {
    id: "apeirix:steel_alloy_block",
    category: "materials",
    name: "Khối Hợp Kim Thép",
  },
  {
    id: "apeirix:raw_silver",
    category: "materials",
    name: "Bạc Thô",
    icon: "textures/silver/raw_silver",
  },
  {
    id: "apeirix:silver_ingot",
    category: "materials",
    name: "Thỏi Bạc",
    icon: "textures/silver/silver_ingot",
  },
  {
    id: "apeirix:silver_nugget",
    category: "materials",
    name: "Mảnh Bạc",
    icon: "textures/silver/silver_nugget",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:silver_ingot_dust",
    category: "materials",
    name: "Bụi Bạc",
    icon: "textures/silver/silver_ingot_dust",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:silver_ingot_dust_pure",
    category: "materials",
    name: "Bụi Bạc Tinh Khiết",
    icon: "textures/silver/silver_ingot_dust_pure",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:silver_block",
    category: "materials",
    name: "Khối Bạc",
  },
  {
    id: "apeirix:silver_ore",
    category: "materials",
    name: "Quặng Bạc",
  },
  {
    id: "apeirix:raw_nickel",
    category: "materials",
    name: "Niken Thô",
    icon: "textures/nickel/raw_nickel",
  },
  {
    id: "apeirix:nickel_ingot",
    category: "materials",
    name: "Thỏi Niken",
    icon: "textures/nickel/nickel_ingot",
  },
  {
    id: "apeirix:nickel_nugget",
    category: "materials",
    name: "Mảnh Niken",
    icon: "textures/nickel/nickel_nugget",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:nickel_ingot_dust",
    category: "materials",
    name: "Bụi Niken",
    icon: "textures/nickel/nickel_ingot_dust",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:nickel_ingot_dust_pure",
    category: "materials",
    name: "Bụi Niken Tinh Khiết",
    icon: "textures/nickel/nickel_ingot_dust_pure",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:raw_lead",
    category: "materials",
    name: "Chì Thô",
    icon: "textures/lead/raw_lead",
  },
  {
    id: "apeirix:lead_ingot",
    category: "materials",
    name: "Thỏi Chì",
    icon: "textures/lead/lead_ingot",
  },
  {
    id: "apeirix:lead_nugget",
    category: "materials",
    name: "Mảnh Chì",
    icon: "textures/lead/lead_nugget",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:lead_ingot_dust",
    category: "materials",
    name: "Bụi Chì",
    icon: "textures/lead/lead_ingot_dust",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:lead_ingot_dust_pure",
    category: "materials",
    name: "Bụi Chì Tinh Khiết",
    icon: "textures/lead/lead_ingot_dust_pure",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:electrum_ingot",
    category: "materials",
    name: "Thỏi Electrum",
    icon: "textures/electrum/electrum_ingot",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:electrum_nugget",
    category: "materials",
    name: "Mảnh Electrum",
    icon: "textures/electrum/electrum_nugget",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:electrum_ingot_dust",
    category: "materials",
    name: "Bụi Electrum",
    icon: "textures/electrum/electrum_ingot_dust",
    info: {
      "Chế tạo": "2 nguyên liệu"
    },
  },
  {
    id: "apeirix:electrum_ingot_dust_pure",
    category: "materials",
    name: "Bụi Electrum Tinh Khiết",
    icon: "textures/electrum/electrum_ingot_dust_pure",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:raw_electrum",
    category: "materials",
    name: "Electrum Thô",
    icon: "textures/electrum/raw_electrum",
  },
  {
    id: "apeirix:invar_ingot",
    category: "materials",
    name: "Thỏi Invar",
    icon: "textures/invar/invar_ingot",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:invar_nugget",
    category: "materials",
    name: "Mảnh Invar",
    icon: "textures/invar/invar_nugget",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:invar_ingot_dust",
    category: "materials",
    name: "Bụi Invar",
    icon: "textures/invar/invar_ingot_dust",
    info: {
      "Chế tạo": "3 nguyên liệu"
    },
  },
  {
    id: "apeirix:invar_ingot_dust_pure",
    category: "materials",
    name: "Bụi Invar Tinh Khiết",
    icon: "textures/invar/invar_ingot_dust_pure",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:raw_invar",
    category: "materials",
    name: "Invar Thô",
    icon: "textures/invar/raw_invar",
  },
  {
    id: "apeirix:raw_platinum",
    category: "materials",
    name: "Bạch Kim Thô",
    icon: "textures/platinum/raw_platinum",
  },
  {
    id: "apeirix:platinum_ingot",
    category: "materials",
    name: "Thỏi Bạch Kim",
    icon: "textures/platinum/platinum_ingot",
  },
  {
    id: "apeirix:platinum_nugget",
    category: "materials",
    name: "Mảnh Bạch Kim",
    icon: "textures/platinum/platinum_nugget",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:platinum_ingot_dust",
    category: "materials",
    name: "Bụi Bạch Kim",
    icon: "textures/platinum/platinum_ingot_dust",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:platinum_ingot_dust_pure",
    category: "materials",
    name: "Bụi Bạch Kim Tinh Khiết",
    icon: "textures/platinum/platinum_ingot_dust_pure",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:raw_cobalt",
    category: "materials",
    name: "Cobalt Thô",
    icon: "textures/cobalt/raw_cobalt",
  },
  {
    id: "apeirix:cobalt_ingot",
    category: "materials",
    name: "Thỏi Cobalt",
    icon: "textures/cobalt/cobalt_ingot",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:cobalt_nugget",
    category: "materials",
    name: "Mảnh Cobalt",
    icon: "textures/cobalt/cobalt_nugget",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:cobalt_ingot_dust",
    category: "materials",
    name: "Bụi Cobalt",
    icon: "textures/cobalt/cobalt_ingot_dust",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:cobalt_ingot_dust_pure",
    category: "materials",
    name: "Bụi Cobalt Tinh Khiết",
    icon: "textures/cobalt/cobalt_ingot_dust_pure",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:raw_ardite",
    category: "materials",
    name: "Ardite Thô",
    icon: "textures/ardite/raw_ardite",
  },
  {
    id: "apeirix:ardite_ingot",
    category: "materials",
    name: "Thỏi Ardite",
    icon: "textures/ardite/ardite_ingot",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:ardite_nugget",
    category: "materials",
    name: "Mảnh Ardite",
    icon: "textures/ardite/ardite_nugget",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:ardite_ingot_dust",
    category: "materials",
    name: "Bụi Ardite",
    icon: "textures/ardite/ardite_ingot_dust",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:ardite_ingot_dust_pure",
    category: "materials",
    name: "Bụi Ardite Tinh Khiết",
    icon: "textures/ardite/ardite_ingot_dust_pure",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:raw_manyullyn",
    category: "materials",
    name: "Manyullyn Thô",
    icon: "textures/manyullyn/raw_manyullyn",
  },
  {
    id: "apeirix:manyullyn_ingot",
    category: "materials",
    name: "Thỏi Manyullyn",
    icon: "textures/manyullyn/manyullyn_ingot",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:manyullyn_nugget",
    category: "materials",
    name: "Mảnh Manyullyn",
    icon: "textures/manyullyn/manyullyn_nugget",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:manyullyn_ingot_dust",
    category: "materials",
    name: "Bụi Manyullyn",
    icon: "textures/manyullyn/manyullyn_ingot_dust",
    info: {
      "Chế tạo": "2 nguyên liệu"
    },
  },
  {
    id: "apeirix:manyullyn_ingot_dust_pure",
    category: "materials",
    name: "Bụi Manyullyn Tinh Khiết",
    icon: "textures/manyullyn/manyullyn_ingot_dust_pure",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:cobblestone_dust",
    category: "materials",
    name: "Bụi Đá Cuội",
    icon: "textures/items/cobblestone_dust",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:deepslate_dust",
    category: "materials",
    name: "Bụi Đá Sâu",
    icon: "textures/items/deepslate_dust",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:netherrack_dust",
    category: "materials",
    name: "Bụi Đá Địa Ngục",
    icon: "textures/items/netherrack_dust",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:coal_dust",
    category: "materials",
    name: "Bụi Than",
    icon: "textures/items/coal_dust",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:copper_ingot_dust",
    category: "materials",
    name: "Bụi Đồng",
    icon: "textures/items/copper_ingot_dust",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:iron_ingot_dust",
    category: "materials",
    name: "Bụi Sắt",
    icon: "textures/items/iron_ingot_dust",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:gold_ingot_dust",
    category: "materials",
    name: "Bụi Vàng",
    icon: "textures/items/gold_ingot_dust",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:tin_ingot_dust",
    category: "materials",
    name: "Bụi Thiếc",
    icon: "textures/items/tin_ingot_dust",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:diamond_dust",
    category: "materials",
    name: "Bụi Kim Cương",
    icon: "textures/items/diamond_dust",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:emerald_dust",
    category: "materials",
    name: "Bụi Ngọc Lục Bảo",
    icon: "textures/items/emerald_dust",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:lapis_block_dust",
    category: "materials",
    name: "Bụi Lưu Ly",
    icon: "textures/items/lapis_block_dust",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:raw_coal",
    category: "materials",
    name: "Than Thô",
    icon: "textures/items/raw_coal",
  },
  {
    id: "apeirix:raw_diamond",
    category: "materials",
    name: "Kim Cương Thô",
    icon: "textures/items/raw_diamond",
  },
  {
    id: "apeirix:raw_emerald",
    category: "materials",
    name: "Ngọc Lục Bảo Thô",
    icon: "textures/items/raw_emerald",
  },
  {
    id: "apeirix:raw_lapis",
    category: "materials",
    name: "Lưu Ly Thô",
    icon: "textures/items/raw_lapis",
  },
  {
    id: "apeirix:coal_dust_pure",
    category: "materials",
    name: "Bụi Than Tinh Khiết",
    icon: "textures/items/coal_dust_pure",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:copper_ingot_dust_pure",
    category: "materials",
    name: "Bụi Đồng Tinh Khiết",
    icon: "textures/items/copper_ingot_dust_pure",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:diamond_dust_pure",
    category: "materials",
    name: "Bụi Kim Cương Tinh Khiết",
    icon: "textures/items/diamond_dust_pure",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:emerald_dust_pure",
    category: "materials",
    name: "Bụi Ngọc Lục Bảo Tinh Khiết",
    icon: "textures/items/emerald_dust_pure",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:gold_ingot_dust_pure",
    category: "materials",
    name: "Bụi Vàng Tinh Khiết",
    icon: "textures/items/gold_ingot_dust_pure",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:iron_ingot_dust_pure",
    category: "materials",
    name: "Bụi Sắt Tinh Khiết",
    icon: "textures/items/iron_ingot_dust_pure",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:lapis_block_dust_pure",
    category: "materials",
    name: "Bụi Lưu Ly Tinh Khiết",
    icon: "textures/items/lapis_block_dust_pure",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:redstone_dust_pure",
    category: "materials",
    name: "Bụi Đá Đỏ Tinh Khiết",
    icon: "textures/items/redstone_dust_pure",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:tin_ingot_dust_pure",
    category: "materials",
    name: "Bụi Thiếc Tinh Khiết",
    icon: "textures/items/tin_ingot_dust_pure",
    info: {
      "Chế tạo": "1 nguyên liệu"
    },
  },
  {
    id: "apeirix:ore_crusher",
    category: "materials",
    name: "ore_crusher",
  },
  {
    id: "apeirix:bronze_pickaxe",
    category: "materials",
    name: "bronze_pickaxe",
  },
  {
    id: "apeirix:bronze_axe",
    category: "materials",
    name: "bronze_axe",
  },
  {
    id: "apeirix:bronze_shovel",
    category: "materials",
    name: "bronze_shovel",
  },
  {
    id: "apeirix:bronze_hoe",
    category: "materials",
    name: "bronze_hoe",
  },
  {
    id: "apeirix:bronze_sword",
    category: "materials",
    name: "bronze_sword",
  },
  {
    id: "apeirix:bronze_spear",
    category: "materials",
    name: "bronze_spear",
  },
  {
    id: "apeirix:steel_alloy_pickaxe",
    category: "materials",
    name: "steel_alloy_pickaxe",
  },
  {
    id: "apeirix:steel_alloy_axe",
    category: "materials",
    name: "steel_alloy_axe",
  },
  {
    id: "apeirix:steel_alloy_shovel",
    category: "materials",
    name: "steel_alloy_shovel",
  },
  {
    id: "apeirix:steel_alloy_hoe",
    category: "materials",
    name: "steel_alloy_hoe",
  },
  {
    id: "apeirix:steel_alloy_sword",
    category: "materials",
    name: "steel_alloy_sword",
  },
  {
    id: "apeirix:copper_hammer",
    category: "materials",
    name: "copper_hammer",
  },
  {
    id: "apeirix:bronze_hammer",
    category: "materials",
    name: "bronze_hammer",
  },
  {
    id: "apeirix:steel_alloy_hammer",
    category: "materials",
    name: "steel_alloy_hammer",
  },
  {
    id: "apeirix:netherite_hammer",
    category: "materials",
    name: "netherite_hammer",
  },
  {
    id: "apeirix:bronze_helmet",
    category: "materials",
    name: "bronze_helmet",
  },
  {
    id: "apeirix:bronze_chestplate",
    category: "materials",
    name: "bronze_chestplate",
  },
  {
    id: "apeirix:bronze_leggings",
    category: "materials",
    name: "bronze_leggings",
  },
  {
    id: "apeirix:bronze_boots",
    category: "materials",
    name: "bronze_boots",
  },
  {
    id: "apeirix:steel_alloy_helmet",
    category: "materials",
    name: "steel_alloy_helmet",
  },
  {
    id: "apeirix:steel_alloy_chestplate",
    category: "materials",
    name: "steel_alloy_chestplate",
  },
  {
    id: "apeirix:steel_alloy_leggings",
    category: "materials",
    name: "steel_alloy_leggings",
  },
  {
    id: "apeirix:steel_alloy_boots",
    category: "materials",
    name: "steel_alloy_boots",
  },
  {
    id: "apeirix:canempty",
    category: "materials",
    name: "Vỏ Đồ Hộp Rỗng",
    icon: "textures/foods/canempty",
    info: {
      "Chế tạo": "Có công thức chế tạo"
    },
  },
  {
    id: "apeirix:candirty",
    category: "materials",
    name: "Vỏ Đồ Hộp Bẩn",
    icon: "textures/foods/candirty",
  },
  {
    id: "apeirix:canned_food",
    category: "materials",
    name: "canned_food",
  },
  {
    id: "apeirix:canned_pumpkin",
    category: "materials",
    name: "canned_pumpkin",
  },
  {
    id: "apeirix:cannedbeets",
    category: "materials",
    name: "cannedbeets",
  },
  {
    id: "apeirix:cannedbread",
    category: "materials",
    name: "cannedbread",
  },
  {
    id: "apeirix:cannedcarrots",
    category: "materials",
    name: "cannedcarrots",
  },
  {
    id: "apeirix:canneddogfood",
    category: "materials",
    name: "canneddogfood",
  },
  {
    id: "apeirix:cannedfish",
    category: "materials",
    name: "cannedfish",
  },
  {
    id: "apeirix:cannedmeal",
    category: "materials",
    name: "cannedmeal",
  },
  {
    id: "apeirix:cannedmushroomsoup",
    category: "materials",
    name: "cannedmushroomsoup",
  },
  {
    id: "apeirix:cannedsalad",
    category: "materials",
    name: "cannedsalad",
  },
  {
    id: "apeirix:achievement_book",
    category: "materials",
    name: "Sách Thành Tựu",
    icon: "textures/items/achievement_book",
  },
  {
    id: "apeirix:wiki_book",
    category: "materials",
    name: "Bách Khoa Toàn Thư",
    icon: "textures/items/wiki_book",
  },
  {
    id: "apeirix:bronze_pickaxe",
    category: "tools",
    name: "Cuốc Đồng Thanh",
    description: "Cuốc đồng thanh dùng để khai thác đá và quặng. Tương đương với cuốc sắt.",
    icon: "textures/tools/bronze_pickaxe",
    info: {
      "Độ bền": 375,
      "Độ phù phép": 18,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:bronze_axe",
    category: "tools",
    name: "Rìu Đồng Thanh",
    icon: "textures/tools/bronze_axe",
    info: {
      "Độ bền": 375,
      "Độ phù phép": 18,
      "Sát thương": 5,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:bronze_shovel",
    category: "tools",
    name: "Xẻng Đồng Thanh",
    icon: "textures/tools/bronze_shovel",
    info: {
      "Độ bền": 375,
      "Độ phù phép": 18,
      "Sát thương": 3,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:bronze_hoe",
    category: "tools",
    name: "Cuốc Đồng Thanh",
    icon: "textures/tools/bronze_hoe",
    info: {
      "Độ bền": 375,
      "Độ phù phép": 18,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:bronze_sword",
    category: "tools",
    name: "Kiếm Đồng Thanh",
    icon: "textures/tools/bronze_sword",
    info: {
      "Độ bền": 375,
      "Độ phù phép": 18,
      "Sát thương": 6,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:bronze_spear",
    category: "tools",
    name: "Giáo Đồng Thanh",
    icon: "textures/tools/bronze_spear",
    info: {
      "Độ bền": 375,
      "Độ phù phép": 18,
      "Sát thương": 3,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:steel_alloy_pickaxe",
    category: "tools",
    name: "Cuốc Hợp Kim Thép",
    icon: "textures/steel_alloy/steel_alloy_pickaxe",
    info: {
      "Độ bền": 750,
      "Độ phù phép": 22,
      "Sát thương": 5,
      "Cấp độ": "diamond"
    },
  },
  {
    id: "apeirix:steel_alloy_axe",
    category: "tools",
    name: "Rìu Hợp Kim Thép",
    icon: "textures/steel_alloy/steel_alloy_axe",
    info: {
      "Độ bền": 750,
      "Độ phù phép": 22,
      "Sát thương": 6,
      "Cấp độ": "diamond"
    },
  },
  {
    id: "apeirix:steel_alloy_shovel",
    category: "tools",
    name: "Xẻng Hợp Kim Thép",
    icon: "textures/steel_alloy/steel_alloy_shovel",
    info: {
      "Độ bền": 750,
      "Độ phù phép": 22,
      "Sát thương": 4,
      "Cấp độ": "diamond"
    },
  },
  {
    id: "apeirix:steel_alloy_hoe",
    category: "tools",
    name: "Cuốc Hợp Kim Thép",
    icon: "textures/steel_alloy/steel_alloy_hoe",
    info: {
      "Độ bền": 750,
      "Độ phù phép": 22,
      "Sát thương": 5,
      "Cấp độ": "diamond"
    },
  },
  {
    id: "apeirix:steel_alloy_sword",
    category: "tools",
    name: "Kiếm Hợp Kim Thép",
    icon: "textures/steel_alloy/steel_alloy_sword",
    info: {
      "Độ bền": 750,
      "Độ phù phép": 22,
      "Sát thương": 7,
      "Cấp độ": "diamond"
    },
  },
  {
    id: "apeirix:silver_pickaxe",
    category: "tools",
    name: "Cuốc Bạc",
    icon: "textures/silver/silver_pickaxe",
    info: {
      "Độ bền": 375,
      "Độ phù phép": 18,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:silver_axe",
    category: "tools",
    name: "Rìu Bạc",
    icon: "textures/silver/silver_axe",
    info: {
      "Độ bền": 375,
      "Độ phù phép": 18,
      "Sát thương": 7,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:silver_shovel",
    category: "tools",
    name: "Xẻng Bạc",
    icon: "textures/silver/silver_shovel",
    info: {
      "Độ bền": 375,
      "Độ phù phép": 18,
      "Sát thương": 3,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:silver_hoe",
    category: "tools",
    name: "Cuốc Bạc",
    icon: "textures/silver/silver_hoe",
    info: {
      "Độ bền": 375,
      "Độ phù phép": 18,
      "Sát thương": 1,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:silver_sword",
    category: "tools",
    name: "Kiếm Bạc",
    icon: "textures/silver/silver_sword",
    info: {
      "Độ bền": 375,
      "Độ phù phép": 18,
      "Sát thương": 6,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:silver_hammer",
    category: "tools",
    name: "Búa Bạc",
    icon: "textures/silver/silver_hammer",
    info: {
      "Độ bền": 375,
      "Độ phù phép": 18,
      "Sát thương": 5,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:nickel_pickaxe",
    category: "tools",
    name: "Cuốc Niken",
    icon: "textures/nickel/nickel_pickaxe",
    info: {
      "Độ bền": 450,
      "Độ phù phép": 14,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:nickel_axe",
    category: "tools",
    name: "Rìu Niken",
    icon: "textures/nickel/nickel_axe",
    info: {
      "Độ bền": 450,
      "Độ phù phép": 14,
      "Sát thương": 5,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:nickel_shovel",
    category: "tools",
    name: "Xẻng Niken",
    icon: "textures/nickel/nickel_shovel",
    info: {
      "Độ bền": 450,
      "Độ phù phép": 14,
      "Sát thương": 3,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:nickel_hoe",
    category: "tools",
    name: "Cuốc Niken",
    icon: "textures/nickel/nickel_hoe",
    info: {
      "Độ bền": 450,
      "Độ phù phép": 14,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:nickel_sword",
    category: "tools",
    name: "Kiếm Niken",
    icon: "textures/nickel/nickel_sword",
    info: {
      "Độ bền": 450,
      "Độ phù phép": 14,
      "Sát thương": 6,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:nickel_hammer",
    category: "tools",
    name: "Búa Niken",
    icon: "textures/nickel/nickel_hammer",
    info: {
      "Độ bền": 675,
      "Độ phù phép": 14,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:lead_pickaxe",
    category: "tools",
    name: "Cuốc Chì",
    icon: "textures/lead/lead_pickaxe",
    info: {
      "Độ bền": 400,
      "Độ phù phép": 12,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:lead_axe",
    category: "tools",
    name: "Rìu Chì",
    icon: "textures/lead/lead_axe",
    info: {
      "Độ bền": 400,
      "Độ phù phép": 12,
      "Sát thương": 5,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:lead_shovel",
    category: "tools",
    name: "Xẻng Chì",
    icon: "textures/lead/lead_shovel",
    info: {
      "Độ bền": 400,
      "Độ phù phép": 12,
      "Sát thương": 3,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:lead_hoe",
    category: "tools",
    name: "Cuốc Chì",
    icon: "textures/lead/lead_hoe",
    info: {
      "Độ bền": 400,
      "Độ phù phép": 12,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:lead_sword",
    category: "tools",
    name: "Kiếm Chì",
    icon: "textures/lead/lead_sword",
    info: {
      "Độ bền": 400,
      "Độ phù phép": 12,
      "Sát thương": 6,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:lead_hammer",
    category: "tools",
    name: "Búa Chì",
    icon: "textures/lead/lead_hammer",
    info: {
      "Độ bền": 600,
      "Độ phù phép": 12,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:electrum_pickaxe",
    category: "tools",
    name: "Cuốc Electrum",
    icon: "textures/electrum/electrum_pickaxe",
    info: {
      "Độ bền": 425,
      "Độ phù phép": 20,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:electrum_axe",
    category: "tools",
    name: "Rìu Electrum",
    icon: "textures/electrum/electrum_axe",
    info: {
      "Độ bền": 425,
      "Độ phù phép": 20,
      "Sát thương": 5,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:electrum_shovel",
    category: "tools",
    name: "Xẻng Electrum",
    icon: "textures/electrum/electrum_shovel",
    info: {
      "Độ bền": 425,
      "Độ phù phép": 20,
      "Sát thương": 3,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:electrum_hoe",
    category: "tools",
    name: "Cuốc Electrum",
    icon: "textures/electrum/electrum_hoe",
    info: {
      "Độ bền": 425,
      "Độ phù phép": 20,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:electrum_sword",
    category: "tools",
    name: "Kiếm Electrum",
    icon: "textures/electrum/electrum_sword",
    info: {
      "Độ bền": 425,
      "Độ phù phép": 20,
      "Sát thương": 6,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:electrum_hammer",
    category: "tools",
    name: "Búa Electrum",
    icon: "textures/electrum/electrum_hammer",
    info: {
      "Độ bền": 640,
      "Độ phù phép": 20,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:invar_pickaxe",
    category: "tools",
    name: "Cuốc Invar",
    icon: "textures/invar/invar_pickaxe",
    info: {
      "Độ bền": 500,
      "Độ phù phép": 10,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:invar_axe",
    category: "tools",
    name: "Rìu Invar",
    icon: "textures/invar/invar_axe",
    info: {
      "Độ bền": 500,
      "Độ phù phép": 10,
      "Sát thương": 5,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:invar_shovel",
    category: "tools",
    name: "Xẻng Invar",
    icon: "textures/invar/invar_shovel",
    info: {
      "Độ bền": 500,
      "Độ phù phép": 10,
      "Sát thương": 3,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:invar_hoe",
    category: "tools",
    name: "Cuốc Invar",
    icon: "textures/invar/invar_hoe",
    info: {
      "Độ bền": 500,
      "Độ phù phép": 10,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:invar_sword",
    category: "tools",
    name: "Kiếm Invar",
    icon: "textures/invar/invar_sword",
    info: {
      "Độ bền": 500,
      "Độ phù phép": 10,
      "Sát thương": 6,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:invar_hammer",
    category: "tools",
    name: "Búa Invar",
    icon: "textures/invar/invar_hammer",
    info: {
      "Độ bền": 750,
      "Độ phù phép": 10,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:platinum_pickaxe",
    category: "tools",
    name: "Cuốc Bạch Kim",
    icon: "textures/platinum/platinum_pickaxe",
    info: {
      "Độ bền": 1600,
      "Độ phù phép": 22,
      "Sát thương": 5,
      "Cấp độ": "diamond"
    },
  },
  {
    id: "apeirix:platinum_axe",
    category: "tools",
    name: "Rìu Bạch Kim",
    icon: "textures/platinum/platinum_axe",
    info: {
      "Độ bền": 1600,
      "Độ phù phép": 22,
      "Sát thương": 7,
      "Cấp độ": "diamond"
    },
  },
  {
    id: "apeirix:platinum_shovel",
    category: "tools",
    name: "Xẻng Bạch Kim",
    icon: "textures/platinum/platinum_shovel",
    info: {
      "Độ bền": 1600,
      "Độ phù phép": 22,
      "Sát thương": 5,
      "Cấp độ": "diamond"
    },
  },
  {
    id: "apeirix:platinum_hoe",
    category: "tools",
    name: "Cuốc Bạch Kim",
    icon: "textures/platinum/platinum_hoe",
    info: {
      "Độ bền": 1600,
      "Độ phù phép": 22,
      "Sát thương": 6,
      "Cấp độ": "diamond"
    },
  },
  {
    id: "apeirix:platinum_sword",
    category: "tools",
    name: "Kiếm Bạch Kim",
    icon: "textures/platinum/platinum_sword",
    info: {
      "Độ bền": 1600,
      "Độ phù phép": 22,
      "Sát thương": 8,
      "Cấp độ": "diamond"
    },
  },
  {
    id: "apeirix:platinum_hammer",
    category: "tools",
    name: "Búa Bạch Kim",
    icon: "textures/platinum/platinum_hammer",
    info: {
      "Độ bền": 2400,
      "Độ phù phép": 22,
      "Sát thương": 6,
      "Cấp độ": "diamond"
    },
  },
  {
    id: "apeirix:tin_pickaxe",
    category: "tools",
    name: "Cuốc Thiếc",
    icon: "textures/tin_tool/tin_pickaxe",
    info: {
      "Độ bền": 375,
      "Độ phù phép": 18,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:tin_axe",
    category: "tools",
    name: "Rìu Thiếc",
    icon: "textures/tin_tool/tin_axe",
    info: {
      "Độ bền": 375,
      "Độ phù phép": 18,
      "Sát thương": 5,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:tin_shovel",
    category: "tools",
    name: "Xẻng Thiếc",
    icon: "textures/tin_tool/tin_shovel",
    info: {
      "Độ bền": 375,
      "Độ phù phép": 18,
      "Sát thương": 3,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:tin_hoe",
    category: "tools",
    name: "Cuốc Thiếc",
    icon: "textures/tin_tool/tin_hoe",
    info: {
      "Độ bền": 375,
      "Độ phù phép": 18,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:tin_sword",
    category: "tools",
    name: "Kiếm Thiếc",
    icon: "textures/tin_tool/tin_sword",
    info: {
      "Độ bền": 375,
      "Độ phù phép": 18,
      "Sát thương": 6,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:tin_hammer",
    category: "tools",
    name: "Búa Thiếc",
    icon: "textures/tin_tool/tin_hammer",
    info: {
      "Độ bền": 562,
      "Độ phù phép": 18,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:cobalt_pickaxe",
    category: "tools",
    name: "Cuốc Cobalt",
    icon: "textures/cobalt/cobalt_pickaxe",
    info: {
      "Độ bền": 500,
      "Độ phù phép": 16,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:cobalt_axe",
    category: "tools",
    name: "Rìu Cobalt",
    icon: "textures/cobalt/cobalt_axe",
    info: {
      "Độ bền": 500,
      "Độ phù phép": 16,
      "Sát thương": 5,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:cobalt_shovel",
    category: "tools",
    name: "Xẻng Cobalt",
    icon: "textures/cobalt/cobalt_shovel",
    info: {
      "Độ bền": 500,
      "Độ phù phép": 16,
      "Sát thương": 3,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:cobalt_hoe",
    category: "tools",
    name: "Cuốc Cobalt",
    icon: "textures/cobalt/cobalt_hoe",
    info: {
      "Độ bền": 500,
      "Độ phù phép": 16,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:cobalt_sword",
    category: "tools",
    name: "Kiếm Cobalt",
    icon: "textures/cobalt/cobalt_sword",
    info: {
      "Độ bền": 500,
      "Độ phù phép": 16,
      "Sát thương": 6,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:cobalt_hammer",
    category: "tools",
    name: "Búa Cobalt",
    icon: "textures/cobalt/cobalt_hammer",
    info: {
      "Độ bền": 750,
      "Độ phù phép": 16,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:ardite_pickaxe",
    category: "tools",
    name: "Cuốc Ardite",
    icon: "textures/ardite/ardite_pickaxe",
    info: {
      "Độ bền": 500,
      "Độ phù phép": 16,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:ardite_axe",
    category: "tools",
    name: "Rìu Ardite",
    icon: "textures/ardite/ardite_axe",
    info: {
      "Độ bền": 500,
      "Độ phù phép": 16,
      "Sát thương": 5,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:ardite_shovel",
    category: "tools",
    name: "Xẻng Ardite",
    icon: "textures/ardite/ardite_shovel",
    info: {
      "Độ bền": 500,
      "Độ phù phép": 16,
      "Sát thương": 3,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:ardite_hoe",
    category: "tools",
    name: "Cuốc Ardite",
    icon: "textures/ardite/ardite_hoe",
    info: {
      "Độ bền": 500,
      "Độ phù phép": 16,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:ardite_sword",
    category: "tools",
    name: "Kiếm Ardite",
    icon: "textures/ardite/ardite_sword",
    info: {
      "Độ bền": 500,
      "Độ phù phép": 16,
      "Sát thương": 6,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:ardite_hammer",
    category: "tools",
    name: "Búa Ardite",
    icon: "textures/ardite/ardite_hammer",
    info: {
      "Độ bền": 750,
      "Độ phù phép": 16,
      "Sát thương": 4,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:manyullyn_pickaxe",
    category: "tools",
    name: "Cuốc Manyullyn",
    icon: "textures/manyullyn/manyullyn_pickaxe",
    info: {
      "Độ bền": 800,
      "Độ phù phép": 18,
      "Sát thương": 5,
      "Cấp độ": "diamond"
    },
  },
  {
    id: "apeirix:manyullyn_axe",
    category: "tools",
    name: "Rìu Manyullyn",
    icon: "textures/manyullyn/manyullyn_axe",
    info: {
      "Độ bền": 800,
      "Độ phù phép": 18,
      "Sát thương": 7,
      "Cấp độ": "diamond"
    },
  },
  {
    id: "apeirix:manyullyn_shovel",
    category: "tools",
    name: "Xẻng Manyullyn",
    icon: "textures/manyullyn/manyullyn_shovel",
    info: {
      "Độ bền": 800,
      "Độ phù phép": 18,
      "Sát thương": 4,
      "Cấp độ": "diamond"
    },
  },
  {
    id: "apeirix:manyullyn_hoe",
    category: "tools",
    name: "Cuốc Manyullyn",
    icon: "textures/manyullyn/manyullyn_hoe",
    info: {
      "Độ bền": 800,
      "Độ phù phép": 18,
      "Sát thương": 5,
      "Cấp độ": "diamond"
    },
  },
  {
    id: "apeirix:manyullyn_sword",
    category: "tools",
    name: "Kiếm Manyullyn",
    icon: "textures/manyullyn/manyullyn_sword",
    info: {
      "Độ bền": 800,
      "Độ phù phép": 18,
      "Sát thương": 8,
      "Cấp độ": "diamond"
    },
  },
  {
    id: "apeirix:manyullyn_hammer",
    category: "tools",
    name: "Búa Manyullyn",
    icon: "textures/manyullyn/manyullyn_hammer",
    info: {
      "Độ bền": 1200,
      "Độ phù phép": 18,
      "Sát thương": 5,
      "Cấp độ": "diamond"
    },
  },
  {
    id: "apeirix:wooden_hammer",
    category: "tools",
    name: "Búa Gỗ",
    icon: "textures/tools/wooden_hammer",
    info: {
      "Độ bền": 59,
      "Độ phù phép": 15,
      "Sát thương": 1,
      "Cấp độ": "wooden"
    },
  },
  {
    id: "apeirix:stone_hammer",
    category: "tools",
    name: "Búa Đá",
    icon: "textures/tools/stone_hammer",
    info: {
      "Độ bền": 131,
      "Độ phù phép": 5,
      "Sát thương": 2,
      "Cấp độ": "stone"
    },
  },
  {
    id: "apeirix:copper_hammer",
    category: "tools",
    name: "Búa Đồng",
    icon: "textures/tools/copper_hammer",
    info: {
      "Độ bền": 200,
      "Độ phù phép": 12,
      "Sát thương": 2,
      "Cấp độ": "stone"
    },
  },
  {
    id: "apeirix:iron_hammer",
    category: "tools",
    name: "Búa Sắt",
    icon: "textures/tools/iron_hammer",
    info: {
      "Độ bền": 250,
      "Độ phù phép": 14,
      "Sát thương": 3,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:golden_hammer",
    category: "tools",
    name: "Búa Vàng",
    icon: "textures/tools/golden_hammer",
    info: {
      "Độ bền": 32,
      "Độ phù phép": 22,
      "Sát thương": 1,
      "Cấp độ": "golden"
    },
  },
  {
    id: "apeirix:bronze_hammer",
    category: "tools",
    name: "Búa Đồng Thanh",
    icon: "textures/tools/bronze_hammer",
    info: {
      "Độ bền": 375,
      "Độ phù phép": 14,
      "Sát thương": 3,
      "Cấp độ": "iron"
    },
  },
  {
    id: "apeirix:steel_alloy_hammer",
    category: "tools",
    name: "Búa Hợp Kim Thép",
    icon: "textures/steel_alloy/steel_alloy_hammer",
    info: {
      "Độ bền": 750,
      "Độ phù phép": 22,
      "Sát thương": 6,
      "Cấp độ": "diamond"
    },
  },
  {
    id: "apeirix:diamond_hammer",
    category: "tools",
    name: "Búa Kim Cương",
    icon: "textures/tools/diamond_hammer",
    info: {
      "Độ bền": 1561,
      "Độ phù phép": 10,
      "Sát thương": 4,
      "Cấp độ": "diamond"
    },
  },
  {
    id: "apeirix:netherite_hammer",
    category: "tools",
    name: "Búa Netherite",
    icon: "textures/tools/netherite_hammer",
    info: {
      "Độ bền": 2031,
      "Độ phù phép": 15,
      "Sát thương": 5,
      "Cấp độ": "netherite"
    },
  },
  {
    id: "apeirix:bronze_helmet",
    category: "armor",
    name: "Mũ Đồng Thanh",
    description: "Mũ giáp đồng thanh bảo vệ đầu. Tương đương với mũ sắt.",
    icon: "textures/armor/items/bronze_helmet",
    info: {
      "Độ bền": 220,
      "Giáp": 2,
      "Độ phù phép": 18,
      "Loại": "Mũ"
    },
  },
  {
    id: "apeirix:bronze_chestplate",
    category: "armor",
    name: "Áo Giáp Đồng Thanh",
    icon: "textures/armor/items/bronze_chestplate",
    info: {
      "Độ bền": 320,
      "Giáp": 5,
      "Độ phù phép": 18,
      "Loại": "Áo giáp"
    },
  },
  {
    id: "apeirix:bronze_leggings",
    category: "armor",
    name: "Quần Đồng Thanh",
    icon: "textures/armor/items/bronze_leggings",
    info: {
      "Độ bền": 300,
      "Giáp": 4,
      "Độ phù phép": 18,
      "Loại": "Quần"
    },
  },
  {
    id: "apeirix:bronze_boots",
    category: "armor",
    name: "Giày Đồng Thanh",
    icon: "textures/armor/items/bronze_boots",
    info: {
      "Độ bền": 260,
      "Giáp": 1,
      "Độ phù phép": 18,
      "Loại": "Giày"
    },
  },
  {
    id: "apeirix:steel_alloy_helmet",
    category: "armor",
    name: "Mũ Hợp Kim Thép",
    icon: "textures/steel_alloy/steel_alloy_helmet",
    info: {
      "Độ bền": 440,
      "Giáp": 3,
      "Độ phù phép": 22,
      "Loại": "Mũ"
    },
  },
  {
    id: "apeirix:steel_alloy_chestplate",
    category: "armor",
    name: "Áo Giáp Hợp Kim Thép",
    icon: "textures/steel_alloy/steel_alloy_chestplate",
    info: {
      "Độ bền": 640,
      "Giáp": 8,
      "Độ phù phép": 22,
      "Loại": "Áo giáp"
    },
  },
  {
    id: "apeirix:steel_alloy_leggings",
    category: "armor",
    name: "Quần Hợp Kim Thép",
    icon: "textures/steel_alloy/steel_alloy_leggings",
    info: {
      "Độ bền": 600,
      "Giáp": 6,
      "Độ phù phép": 22,
      "Loại": "Quần"
    },
  },
  {
    id: "apeirix:steel_alloy_boots",
    category: "armor",
    name: "Giày Hợp Kim Thép",
    icon: "textures/steel_alloy/steel_alloy_boots",
    info: {
      "Độ bền": 520,
      "Giáp": 3,
      "Độ phù phép": 22,
      "Loại": "Giày"
    },
  },
  {
    id: "apeirix:silver_helmet",
    category: "armor",
    name: "Mũ Bạc",
    icon: "textures/silver/silver_helmet",
    info: {
      "Độ bền": 220,
      "Giáp": 2,
      "Độ phù phép": 18,
      "Loại": "Mũ"
    },
  },
  {
    id: "apeirix:silver_chestplate",
    category: "armor",
    name: "Áo Giáp Bạc",
    icon: "textures/silver/silver_chestplate",
    info: {
      "Độ bền": 320,
      "Giáp": 6,
      "Độ phù phép": 18,
      "Loại": "Áo giáp"
    },
  },
  {
    id: "apeirix:silver_leggings",
    category: "armor",
    name: "Quần Bạc",
    icon: "textures/silver/silver_leggings",
    info: {
      "Độ bền": 300,
      "Giáp": 5,
      "Độ phù phép": 18,
      "Loại": "Quần"
    },
  },
  {
    id: "apeirix:silver_boots",
    category: "armor",
    name: "Giày Bạc",
    icon: "textures/silver/silver_boots",
    info: {
      "Độ bền": 260,
      "Giáp": 2,
      "Độ phù phép": 18,
      "Loại": "Giày"
    },
  },
  {
    id: "apeirix:nickel_helmet",
    category: "armor",
    name: "Mũ Niken",
    icon: "textures/nickel/nickel_helmet",
    info: {
      "Độ bền": 220,
      "Giáp": 2,
      "Độ phù phép": 14,
      "Loại": "Mũ"
    },
  },
  {
    id: "apeirix:nickel_chestplate",
    category: "armor",
    name: "Áo Giáp Niken",
    icon: "textures/nickel/nickel_chestplate",
    info: {
      "Độ bền": 320,
      "Giáp": 5,
      "Độ phù phép": 14,
      "Loại": "Áo giáp"
    },
  },
  {
    id: "apeirix:nickel_leggings",
    category: "armor",
    name: "Quần Niken",
    icon: "textures/nickel/nickel_leggings",
    info: {
      "Độ bền": 300,
      "Giáp": 4,
      "Độ phù phép": 14,
      "Loại": "Quần"
    },
  },
  {
    id: "apeirix:nickel_boots",
    category: "armor",
    name: "Giày Niken",
    icon: "textures/nickel/nickel_boots",
    info: {
      "Độ bền": 260,
      "Giáp": 1,
      "Độ phù phép": 14,
      "Loại": "Giày"
    },
  },
  {
    id: "apeirix:lead_helmet",
    category: "armor",
    name: "Mũ Chì",
    icon: "textures/lead/lead_helmet",
    info: {
      "Độ bền": 220,
      "Giáp": 2,
      "Độ phù phép": 12,
      "Loại": "Mũ"
    },
  },
  {
    id: "apeirix:lead_chestplate",
    category: "armor",
    name: "Áo Giáp Chì",
    icon: "textures/lead/lead_chestplate",
    info: {
      "Độ bền": 320,
      "Giáp": 5,
      "Độ phù phép": 12,
      "Loại": "Áo giáp"
    },
  },
  {
    id: "apeirix:lead_leggings",
    category: "armor",
    name: "Quần Chì",
    icon: "textures/lead/lead_leggings",
    info: {
      "Độ bền": 300,
      "Giáp": 4,
      "Độ phù phép": 12,
      "Loại": "Quần"
    },
  },
  {
    id: "apeirix:lead_boots",
    category: "armor",
    name: "Giày Chì",
    icon: "textures/lead/lead_boots",
    info: {
      "Độ bền": 260,
      "Giáp": 1,
      "Độ phù phép": 12,
      "Loại": "Giày"
    },
  },
  {
    id: "apeirix:electrum_helmet",
    category: "armor",
    name: "Mũ Electrum",
    icon: "textures/electrum/electrum_helmet",
    info: {
      "Độ bền": 220,
      "Giáp": 2,
      "Độ phù phép": 20,
      "Loại": "Mũ"
    },
  },
  {
    id: "apeirix:electrum_chestplate",
    category: "armor",
    name: "Áo Giáp Electrum",
    icon: "textures/electrum/electrum_chestplate",
    info: {
      "Độ bền": 320,
      "Giáp": 5,
      "Độ phù phép": 20,
      "Loại": "Áo giáp"
    },
  },
  {
    id: "apeirix:electrum_leggings",
    category: "armor",
    name: "Quần Electrum",
    icon: "textures/electrum/electrum_leggings",
    info: {
      "Độ bền": 300,
      "Giáp": 4,
      "Độ phù phép": 20,
      "Loại": "Quần"
    },
  },
  {
    id: "apeirix:electrum_boots",
    category: "armor",
    name: "Giày Electrum",
    icon: "textures/electrum/electrum_boots",
    info: {
      "Độ bền": 260,
      "Giáp": 1,
      "Độ phù phép": 20,
      "Loại": "Giày"
    },
  },
  {
    id: "apeirix:invar_helmet",
    category: "armor",
    name: "Mũ Invar",
    icon: "textures/invar/invar_helmet",
    info: {
      "Độ bền": 220,
      "Giáp": 2,
      "Độ phù phép": 10,
      "Loại": "Mũ"
    },
  },
  {
    id: "apeirix:invar_chestplate",
    category: "armor",
    name: "Áo Giáp Invar",
    icon: "textures/invar/invar_chestplate",
    info: {
      "Độ bền": 320,
      "Giáp": 5,
      "Độ phù phép": 10,
      "Loại": "Áo giáp"
    },
  },
  {
    id: "apeirix:invar_leggings",
    category: "armor",
    name: "Quần Invar",
    icon: "textures/invar/invar_leggings",
    info: {
      "Độ bền": 300,
      "Giáp": 4,
      "Độ phù phép": 10,
      "Loại": "Quần"
    },
  },
  {
    id: "apeirix:invar_boots",
    category: "armor",
    name: "Giày Invar",
    icon: "textures/invar/invar_boots",
    info: {
      "Độ bền": 260,
      "Giáp": 1,
      "Độ phù phép": 10,
      "Loại": "Giày"
    },
  },
  {
    id: "apeirix:platinum_helmet",
    category: "armor",
    name: "Mũ Bạch Kim",
    icon: "textures/platinum/platinum_helmet",
    info: {
      "Độ bền": 440,
      "Giáp": 3,
      "Độ phù phép": 22,
      "Loại": "Mũ"
    },
  },
  {
    id: "apeirix:platinum_chestplate",
    category: "armor",
    name: "Áo Giáp Bạch Kim",
    icon: "textures/platinum/platinum_chestplate",
    info: {
      "Độ bền": 640,
      "Giáp": 8,
      "Độ phù phép": 22,
      "Loại": "Áo giáp"
    },
  },
  {
    id: "apeirix:platinum_leggings",
    category: "armor",
    name: "Quần Bạch Kim",
    icon: "textures/platinum/platinum_leggings",
    info: {
      "Độ bền": 600,
      "Giáp": 6,
      "Độ phù phép": 22,
      "Loại": "Quần"
    },
  },
  {
    id: "apeirix:platinum_boots",
    category: "armor",
    name: "Giày Bạch Kim",
    icon: "textures/platinum/platinum_boots",
    info: {
      "Độ bền": 520,
      "Giáp": 3,
      "Độ phù phép": 22,
      "Loại": "Giày"
    },
  },
  {
    id: "apeirix:tin_helmet",
    category: "armor",
    name: "Mũ Thiếc",
    icon: "textures/tin_tool/tin_helmet",
    info: {
      "Độ bền": 220,
      "Giáp": 2,
      "Độ phù phép": 18,
      "Loại": "Mũ"
    },
  },
  {
    id: "apeirix:tin_chestplate",
    category: "armor",
    name: "Áo Giáp Thiếc",
    icon: "textures/tin_tool/tin_chestplate",
    info: {
      "Độ bền": 320,
      "Giáp": 5,
      "Độ phù phép": 18,
      "Loại": "Áo giáp"
    },
  },
  {
    id: "apeirix:tin_leggings",
    category: "armor",
    name: "Quần Thiếc",
    icon: "textures/tin_tool/tin_leggings",
    info: {
      "Độ bền": 300,
      "Giáp": 4,
      "Độ phù phép": 18,
      "Loại": "Quần"
    },
  },
  {
    id: "apeirix:tin_boots",
    category: "armor",
    name: "Giày Thiếc",
    icon: "textures/tin_tool/tin_boots",
    info: {
      "Độ bền": 260,
      "Giáp": 1,
      "Độ phù phép": 18,
      "Loại": "Giày"
    },
  },
  {
    id: "apeirix:cobalt_helmet",
    category: "armor",
    name: "Mũ Cobalt",
    icon: "textures/cobalt/cobalt_helmet",
    info: {
      "Độ bền": 220,
      "Giáp": 2,
      "Độ phù phép": 16,
      "Loại": "Mũ"
    },
  },
  {
    id: "apeirix:cobalt_chestplate",
    category: "armor",
    name: "Áo Giáp Cobalt",
    icon: "textures/cobalt/cobalt_chestplate",
    info: {
      "Độ bền": 320,
      "Giáp": 5,
      "Độ phù phép": 16,
      "Loại": "Áo giáp"
    },
  },
  {
    id: "apeirix:cobalt_leggings",
    category: "armor",
    name: "Quần Cobalt",
    icon: "textures/cobalt/cobalt_leggings",
    info: {
      "Độ bền": 300,
      "Giáp": 4,
      "Độ phù phép": 16,
      "Loại": "Quần"
    },
  },
  {
    id: "apeirix:cobalt_boots",
    category: "armor",
    name: "Giày Cobalt",
    icon: "textures/cobalt/cobalt_boots",
    info: {
      "Độ bền": 260,
      "Giáp": 1,
      "Độ phù phép": 16,
      "Loại": "Giày"
    },
  },
  {
    id: "apeirix:ardite_helmet",
    category: "armor",
    name: "Mũ Ardite",
    icon: "textures/ardite/ardite_helmet",
    info: {
      "Độ bền": 220,
      "Giáp": 2,
      "Độ phù phép": 16,
      "Loại": "Mũ"
    },
  },
  {
    id: "apeirix:ardite_chestplate",
    category: "armor",
    name: "Áo Giáp Ardite",
    icon: "textures/ardite/ardite_chestplate",
    info: {
      "Độ bền": 320,
      "Giáp": 5,
      "Độ phù phép": 16,
      "Loại": "Áo giáp"
    },
  },
  {
    id: "apeirix:ardite_leggings",
    category: "armor",
    name: "Quần Ardite",
    icon: "textures/ardite/ardite_leggings",
    info: {
      "Độ bền": 300,
      "Giáp": 4,
      "Độ phù phép": 16,
      "Loại": "Quần"
    },
  },
  {
    id: "apeirix:ardite_boots",
    category: "armor",
    name: "Giày Ardite",
    icon: "textures/ardite/ardite_boots",
    info: {
      "Độ bền": 260,
      "Giáp": 1,
      "Độ phù phép": 16,
      "Loại": "Giày"
    },
  },
  {
    id: "apeirix:manyullyn_helmet",
    category: "armor",
    name: "Mũ Manyullyn",
    icon: "textures/manyullyn/manyullyn_helmet",
    info: {
      "Độ bền": 280,
      "Giáp": 3,
      "Độ phù phép": 18,
      "Loại": "Mũ"
    },
  },
  {
    id: "apeirix:manyullyn_chestplate",
    category: "armor",
    name: "Áo Giáp Manyullyn",
    icon: "textures/manyullyn/manyullyn_chestplate",
    info: {
      "Độ bền": 400,
      "Giáp": 7,
      "Độ phù phép": 18,
      "Loại": "Áo giáp"
    },
  },
  {
    id: "apeirix:manyullyn_leggings",
    category: "armor",
    name: "Quần Manyullyn",
    icon: "textures/manyullyn/manyullyn_leggings",
    info: {
      "Độ bền": 375,
      "Giáp": 5,
      "Độ phù phép": 18,
      "Loại": "Quần"
    },
  },
  {
    id: "apeirix:manyullyn_boots",
    category: "armor",
    name: "Giày Manyullyn",
    icon: "textures/manyullyn/manyullyn_boots",
    info: {
      "Độ bền": 325,
      "Giáp": 2,
      "Độ phù phép": 18,
      "Loại": "Giày"
    },
  },
  {
    id: "apeirix:canned_food",
    category: "foods",
    name: "Đồ Hộp Thịt",
    icon: "textures/foods/canned_food",
    info: {
      "Dinh dưỡng": 10,
      "Độ no": 12.8
    },
  },
  {
    id: "apeirix:canned_pumpkin",
    category: "foods",
    name: "Đồ Hộp Bí Ngô",
    icon: "textures/foods/canned_pumpkin",
    info: {
      "Dinh dưỡng": 4,
      "Độ no": 4.8,
      "Hiệu ứng": "Kháng lửa"
    },
  },
  {
    id: "apeirix:cannedbeets",
    category: "foods",
    name: "Đồ Hộp Củ Dền",
    icon: "textures/foods/cannedbeets",
    info: {
      "Dinh dưỡng": 6,
      "Độ no": 7.2
    },
  },
  {
    id: "apeirix:cannedbread",
    category: "foods",
    name: "Đồ Hộp Bánh Mì",
    icon: "textures/foods/cannedbread",
    info: {
      "Dinh dưỡng": 5,
      "Độ no": 6
    },
  },
  {
    id: "apeirix:cannedcarrots",
    category: "foods",
    name: "Đồ Hộp Cà Rốt",
    icon: "textures/foods/cannedcarrots",
    info: {
      "Dinh dưỡng": 4,
      "Độ no": 4.8,
      "Hiệu ứng": "Nhìn đêm"
    },
  },
  {
    id: "apeirix:canneddogfood",
    category: "foods",
    name: "Đồ Hộp Thức Ăn Chó",
    icon: "textures/foods/canneddogfood",
    info: {
      "Dinh dưỡng": 2,
      "Độ no": 0.4,
      "Hiệu ứng": "nausea"
    },
  },
  {
    id: "apeirix:cannedfish",
    category: "foods",
    name: "Đồ Hộp Cá",
    icon: "textures/foods/cannedfish",
    info: {
      "Dinh dưỡng": 5,
      "Độ no": 6,
      "Hiệu ứng": "Thở dưới nước"
    },
  },
  {
    id: "apeirix:cannedmeal",
    category: "foods",
    name: "Đồ Hộp Bữa Ăn",
    icon: "textures/foods/cannedmeal",
    info: {
      "Dinh dưỡng": 12,
      "Độ no": 16,
      "Hiệu ứng": "Hồi máu"
    },
  },
  {
    id: "apeirix:cannedmushroomsoup",
    category: "foods",
    name: "Đồ Hộp Súp Nấm",
    icon: "textures/foods/cannedmushroomsoup",
    info: {
      "Dinh dưỡng": 6,
      "Độ no": 7.2
    },
  },
  {
    id: "apeirix:cannedsalad",
    category: "foods",
    name: "Đồ Hộp Salad",
    icon: "textures/foods/cannedsalad",
    info: {
      "Dinh dưỡng": 3,
      "Độ no": 3.6,
      "Hiệu ứng": "health_boost"
    },
  },
  {
    id: "apeirix:luncheonmeat",
    category: "foods",
    name: "Đồ Hộp Thịt Nguội",
    icon: "textures/foods/luncheonmeat",
    info: {
      "Dinh dưỡng": 8,
      "Độ no": 10.4,
      "Hiệu ứng": "No lâu"
    },
  },
  {
    id: "apeirix:fruit_salad",
    category: "foods",
    name: "Đồ Hộp Salad Trái Cây",
    icon: "textures/foods/fruit_salad",
    info: {
      "Dinh dưỡng": 6,
      "Độ no": 7.2,
      "Hiệu ứng": "Tăng tốc"
    },
  },
  {
    id: "apeirix:chickensoup",
    category: "foods",
    name: "Đồ Hộp Súp Gà",
    description: "Súp gà đóng hộp. Cho hiệu ứng hồi máu.",
    icon: "textures/foods/chickensoup",
    info: {
      "Dinh dưỡng": 7,
      "Độ no": 8.4,
      "Hiệu ứng": "Hồi máu"
    },
  },
  {
    id: "apeirix:cookies",
    category: "foods",
    name: "Đồ Hộp Bánh Quy",
    icon: "textures/foods/cookies",
    info: {
      "Dinh dưỡng": 4,
      "Độ no": 4.8,
      "Hiệu ứng": "Đào nhanh"
    },
  }
];

/**
 * Generated block info data
 * Used by DisplayHandler to show block information
 */
export const GENERATED_BLOCKS = [
  {
    blockId: "apeirix:tin_ore",
    blockType: "ore",
    displayName: "Quặng Thiếc"
  },
  {
    blockId: "apeirix:deepslate_tin_ore",
    blockType: "ore",
    displayName: "Quặng Thiếc Đá Sâu"
  },
  {
    blockId: "apeirix:silver_ore",
    blockType: "ore",
    displayName: "Quặng Bạc"
  },
  {
    blockId: "apeirix:deepslate_silver_ore",
    blockType: "ore",
    displayName: "Quặng Bạc Đá Sâu"
  },
  {
    blockId: "apeirix:nickel_ore",
    blockType: "ore",
    displayName: "Quặng Niken"
  },
  {
    blockId: "apeirix:deepslate_nickel_ore",
    blockType: "ore",
    displayName: "Quặng Niken Đá Sâu"
  },
  {
    blockId: "apeirix:lead_ore",
    blockType: "ore",
    displayName: "Quặng Chì"
  },
  {
    blockId: "apeirix:deepslate_lead_ore",
    blockType: "ore",
    displayName: "Quặng Chì Đá Sâu"
  },
  {
    blockId: "apeirix:platinum_ore",
    blockType: "ore",
    displayName: "Quặng Bạch Kim"
  },
  {
    blockId: "apeirix:deepslate_platinum_ore",
    blockType: "ore",
    displayName: "Quặng Bạch Kim Đá Sâu"
  },
  {
    blockId: "apeirix:cobalt_ore",
    blockType: "ore",
    displayName: "Quặng Cobalt"
  },
  {
    blockId: "apeirix:deepslate_cobalt_ore",
    blockType: "ore",
    displayName: "deepslate_cobalt_ore"
  },
  {
    blockId: "apeirix:ardite_ore",
    blockType: "ore",
    displayName: "Quặng Ardite"
  },
  {
    blockId: "apeirix:deepslate_ardite_ore",
    blockType: "ore",
    displayName: "deepslate_ardite_ore"
  },
  {
    blockId: "apeirix:tin_block",
    blockType: "storage",
    displayName: "Khối Thiếc"
  },
  {
    blockId: "apeirix:bronze_block",
    blockType: "storage",
    displayName: "Khối Đồng Thanh"
  },
  {
    blockId: "apeirix:alloy_mixing_table",
    blockType: "other",
    displayName: "alloy_mixing_table"
  },
  {
    blockId: "apeirix:steel_alloy_block",
    blockType: "storage",
    displayName: "Khối Hợp Kim Thép"
  },
  {
    blockId: "apeirix:silver_block",
    blockType: "storage",
    displayName: "Khối Bạc"
  },
  {
    blockId: "apeirix:nickel_block",
    blockType: "storage",
    displayName: "Khối Niken"
  },
  {
    blockId: "apeirix:lead_block",
    blockType: "storage",
    displayName: "Khối Chì"
  },
  {
    blockId: "apeirix:electrum_block",
    blockType: "storage",
    displayName: "Khối Electrum"
  },
  {
    blockId: "apeirix:invar_block",
    blockType: "storage",
    displayName: "Khối Invar"
  },
  {
    blockId: "apeirix:platinum_block",
    blockType: "storage",
    displayName: "Khối Bạch Kim"
  },
  {
    blockId: "apeirix:cobalt_block",
    blockType: "storage",
    displayName: "Khối Cobalt"
  },
  {
    blockId: "apeirix:ardite_block",
    blockType: "storage",
    displayName: "Khối Ardite"
  },
  {
    blockId: "apeirix:manyullyn_block",
    blockType: "storage",
    displayName: "Khối Manyullyn"
  },
  {
    blockId: "apeirix:ore_crusher_mk1",
    blockType: "machine",
    machineType: "ore_crusher_mk1",
    displayName: "Máy Nghiền Quặng MK1"
  },
  {
    blockId: "apeirix:ore_crusher_mk2",
    blockType: "machine",
    machineType: "ore_crusher_mk2",
    displayName: "Máy Nghiền Quặng MK2"
  },
  {
    blockId: "apeirix:ore_crusher_mk3",
    blockType: "machine",
    machineType: "ore_crusher_mk3",
    displayName: "Máy Nghiền Quặng MK3"
  },
  {
    blockId: "apeirix:ore_sieve",
    blockType: "machine",
    machineType: "ore_sieve",
    displayName: "Rây Sàng Quặng"
  },
  {
    blockId: "apeirix:ore_sieve_on",
    blockType: "machine",
    machineType: "ore_sieve",
    displayName: "Rây Sàng Quặng"
  },
  {
    blockId: "apeirix:ore_washer",
    blockType: "machine",
    machineType: "ore_washer",
    displayName: "Máy Rửa Quặng"
  },
  {
    blockId: "apeirix:compressor",
    blockType: "machine",
    machineType: "compressor",
    displayName: "Máy Nén"
  },
  {
    blockId: "apeirix:compressor_on",
    blockType: "machine",
    machineType: "compressor",
    displayName: "Máy Nén"
  },
  {
    blockId: "apeirix:crusher",
    blockType: "machine",
    machineType: "crusher",
    displayName: "Máy Nghiền"
  },
  {
    blockId: "apeirix:crusher_on",
    blockType: "machine",
    machineType: "crusher",
    displayName: "Máy Nghiền"
  }
];

/**
 * Generated hammer mining data
 */
export const GENERATED_HAMMER_MINING = [
  // No hammer mining data generated
];

/**
 * Generated hammer tool IDs
 * DEPRECATED: Use AttributeSystem with 'hammer_mining' attribute instead
 * Kept for backward compatibility only
 */
export const GENERATED_HAMMER_IDS = [
  // DEPRECATED - Use GENERATED_ATTRIBUTES['hammer_mining'] instead
];

/**
 * Generated brass sifter recipes
 */
export const GENERATED_BRASS_SIFTER = [
  // No brass sifter recipes generated
];

/**
 * Generated Rust Mite edible items
 * DEPRECATED: Use AttributeSystem with 'rust_mite_edible' attribute instead
 * Kept for backward compatibility only
 */
export const GENERATED_RUST_MITE_EDIBLE_ITEMS = [
  // DEPRECATED - Use GENERATED_ATTRIBUTES['rust_mite_edible'] instead
];
