/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by addon-generator CLI
 * 
 * Để thêm/sửa/xóa processing recipes:
 * 1. Edit YAML files trong addon-generator/configs/materials/processing/
 * 2. Run: bun run dev compile configs/addon.yaml
 * 3. File này sẽ được regenerate tự động
 */

export interface ProcessingRecipe {
  input: string;
  output: string;
  processingTime: number;
}

/**
 * Generated processing recipes grouped by machine type
 */
export const GENERATED_PROCESSING_RECIPES: Record<string, ProcessingRecipe[]> = {
  "compressor": [
    { input: "apeirix:steel_alloy_ingot", output: "apeirix:steel_alloy_plate", processingTime: 60 }
  ],
};
