/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by addon-generator CLI
 * 
 * Để thêm/sửa/xóa attributes:
 * 1. Edit field 'attributes' trong YAML files (configs/materials/, configs/tools/, etc.)
 * 2. Run: bun run dev compile configs/addon.yaml
 * 3. File này sẽ được regenerate tự động
 * 
 * Generated: 2026-03-05T06:07:18.917Z
 * Total attributes: 0
 * Total items with attributes: 0
 */

// Attribute data for each item
export interface AttributeItemData {
  itemId: string;
  config?: any; // Optional config object
}

/**
 * Attribute mapping: attributeId -> array of items with config
 * 
 * Usage:
 * - Check if item has attribute: hasAttribute(itemId, 'hammer_mining')
 * - Get all items with attribute: getItemsWithAttribute('rust_mite_edible')
 * - Get attribute config: getAttributeConfig(itemId, 'undead_slayer')
 */
export const GENERATED_ATTRIBUTES: Record<string, AttributeItemData[]> = {

};

/**
 * Helper: Check if item has specific attribute
 */
export function hasAttribute(itemId: string, attributeId: string): boolean {
  const items = GENERATED_ATTRIBUTES[attributeId];
  return items ? items.some(item => item.itemId === itemId) : false;
}

/**
 * Helper: Get all attributes for an item
 */
export function getItemAttributes(itemId: string): string[] {
  const attributes: string[] = [];
  for (const [attrId, items] of Object.entries(GENERATED_ATTRIBUTES)) {
    if (items.some(item => item.itemId === itemId)) {
      attributes.push(attrId);
    }
  }
  return attributes;
}

/**
 * Helper: Get all items with specific attribute (returns itemIds only)
 */
export function getItemsWithAttribute(attributeId: string): string[] {
  const items = GENERATED_ATTRIBUTES[attributeId] || [];
  return items.map(item => item.itemId);
}

/**
 * Helper: Get attribute config for specific item
 */
export function getAttributeConfig(itemId: string, attributeId: string): any | undefined {
  const items = GENERATED_ATTRIBUTES[attributeId];
  if (!items) return undefined;
  
  const itemData = items.find(item => item.itemId === itemId);
  return itemData?.config;
}

/**
 * Helper: Get all items with attribute including config
 */
export function getAttributeItems(attributeId: string): AttributeItemData[] {
  return GENERATED_ATTRIBUTES[attributeId] || [];
}
