/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by addon-generator CLI
 * 
 * Để thêm/sửa/xóa content:
 * 1. Edit YAML files trong addon-generator/configs/
 * 2. Run: bun run dev compile configs/addon.yaml
 * 3. File này sẽ được regenerate tự động
 */

/**
 * Generated ore data
 */
export const GENERATED_ORES = [
  // No ores generated
];

/**
 * Generated tool data
 */
export const GENERATED_TOOLS = [
  // No tools generated
];

/**
 * Generated food data
 */
export const GENERATED_FOODS = [
  // No foods with effects generated
];

/**
 * Generated wiki item data
 */
export const GENERATED_WIKI_ITEMS = [
  // No wiki items generated
];

/**
 * Generated block info data
 * Used by DisplayHandler to show block information
 */
export const GENERATED_BLOCKS = [
  // No blocks generated
];

/**
 * Generated hammer mining data
 */
export const GENERATED_HAMMER_MINING = [
  // No hammer mining data generated
];

/**
 * Generated hammer tool IDs
 * DEPRECATED: Use AttributeSystem with 'hammer_mining' attribute instead
 * Kept for backward compatibility only
 */
export const GENERATED_HAMMER_IDS = [
  // DEPRECATED - Use GENERATED_ATTRIBUTES['hammer_mining'] instead
];

/**
 * Generated brass sifter recipes
 */
export const GENERATED_BRASS_SIFTER = [
  // No brass sifter recipes generated
];

/**
 * Generated Rust Mite edible items
 * DEPRECATED: Use AttributeSystem with 'rust_mite_edible' attribute instead
 * Kept for backward compatibility only
 */
export const GENERATED_RUST_MITE_EDIBLE_ITEMS = [
  // DEPRECATED - Use GENERATED_ATTRIBUTES['rust_mite_edible'] instead
];

/**
 * Generated armor data
 * Used by ArmorToughnessSystem for custom toughness calculation
 */
export const GENERATED_ARMORS = [
  // No armor generated
];
