/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by addon-generator CLI
 * 
 * Để thêm/sửa/xóa attributes:
 * 1. Edit field 'attributes' trong YAML files (configs/materials/, configs/tools/, etc.)
 * 2. Run: bun run dev compile configs/addon.yaml
 * 3. File này sẽ được regenerate tự động
 * 
 * Generated: 2026-02-28T14:57:50.581Z
 * Total attributes: 3
 * Total items with attributes: 88
 */

/**
 * Attribute mapping: attributeId -> itemIds[]
 * 
 * Usage:
 * - Check if item has attribute: GENERATED_ATTRIBUTES['hammer_mining'].includes(itemId)
 * - Get all items with attribute: GENERATED_ATTRIBUTES['rust_mite_edible']
 */
export const GENERATED_ATTRIBUTES: Record<string, string[]> = {
  'hammer_mining': [
  'apeirix:engineering_hammer',
  'apeirix:ardite_hammer',
  'apeirix:bronze_hammer',
  'apeirix:cobalt_hammer',
  'apeirix:copper_hammer',
  'apeirix:diamond_hammer',
  'apeirix:electrum_hammer',
  'apeirix:golden_hammer',
  'apeirix:invar_hammer',
  'apeirix:iron_hammer',
  'apeirix:lead_hammer',
  'apeirix:manyullyn_hammer',
  'apeirix:netherite_hammer',
  'apeirix:nickel_hammer',
  'apeirix:platinum_hammer',
  'apeirix:silver_hammer',
  'apeirix:steel_alloy_hammer',
  'apeirix:stone_hammer',
  'apeirix:tin_hammer',
  'apeirix:wooden_hammer'
  ],
  'rust_mite_edible': [
  'apeirix:ardite_ingot_dust',
  'apeirix:ardite_ingot_dust_pure',
  'apeirix:bronze_ingot_dust',
  'apeirix:bronze_ingot_dust_pure',
  'apeirix:coal_dust',
  'apeirix:coal_dust_pure',
  'apeirix:cobalt_ingot_dust',
  'apeirix:cobalt_ingot_dust_pure',
  'apeirix:cobblestone_dust',
  'apeirix:copper_ingot_dust',
  'apeirix:copper_ingot_dust_pure',
  'apeirix:deepslate_dust',
  'apeirix:diamond_dust',
  'apeirix:diamond_dust_pure',
  'apeirix:electrum_ingot_dust',
  'apeirix:electrum_ingot_dust_pure',
  'apeirix:emerald_dust',
  'apeirix:emerald_dust_pure',
  'apeirix:gold_ingot_dust',
  'apeirix:gold_ingot_dust_pure',
  'apeirix:invar_ingot_dust',
  'apeirix:invar_ingot_dust_pure',
  'apeirix:iron_ingot_dust',
  'apeirix:iron_ingot_dust_pure',
  'apeirix:lapis_block_dust',
  'apeirix:lapis_block_dust_pure',
  'apeirix:lead_ingot_dust',
  'apeirix:lead_ingot_dust_pure',
  'apeirix:manyullyn_ingot_dust',
  'apeirix:manyullyn_ingot_dust_pure',
  'apeirix:netherrack_dust',
  'apeirix:nickel_ingot_dust',
  'apeirix:nickel_ingot_dust_pure',
  'apeirix:raw_coal',
  'apeirix:raw_diamond',
  'apeirix:raw_emerald',
  'apeirix:raw_lapis',
  'apeirix:redstone_dust_pure',
  'apeirix:silver_ingot_dust',
  'apeirix:silver_ingot_dust_pure',
  'apeirix:steel_alloy_dust',
  'apeirix:steel_alloy_dust_pure',
  'apeirix:tin_ingot_dust',
  'apeirix:tin_ingot_dust_pure',
  'apeirix:raw_bronze',
  'apeirix:raw_electrum',
  'apeirix:raw_invar',
  'apeirix:raw_manyullyn',
  'apeirix:raw_silver',
  'apeirix:raw_steel',
  'apeirix:raw_tin',
  'apeirix:candirty',
  'apeirix:canempty',
  'apeirix:cannedbeets',
  'apeirix:cannedbread',
  'apeirix:cannedcarrots',
  'apeirix:canneddogfood',
  'apeirix:cannedfish',
  'apeirix:cannedmeal',
  'apeirix:cannedmushroomsoup',
  'apeirix:cannedsalad',
  'apeirix:canned_food',
  'apeirix:canned_pumpkin',
  'apeirix:chickensoup',
  'apeirix:cookies',
  'apeirix:fruit_salad',
  'apeirix:luncheonmeat'
  ],
  'undead_slayer': [
  'apeirix:silver_sword'
  ]
};

/**
 * Helper: Check if item has specific attribute
 */
export function hasAttribute(itemId: string, attributeId: string): boolean {
  const items = GENERATED_ATTRIBUTES[attributeId];
  return items ? items.includes(itemId) : false;
}

/**
 * Helper: Get all attributes for an item
 */
export function getItemAttributes(itemId: string): string[] {
  const attributes: string[] = [];
  for (const [attrId, itemIds] of Object.entries(GENERATED_ATTRIBUTES)) {
    if (itemIds.includes(itemId)) {
      attributes.push(attrId);
    }
  }
  return attributes;
}

/**
 * Helper: Get all items with specific attribute
 */
export function getItemsWithAttribute(attributeId: string): string[] {
  return GENERATED_ATTRIBUTES[attributeId] || [];
}
