/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by addon-generator CLI
 * 
 * Để thêm/sửa/xóa content:
 * 1. Edit YAML files trong addon-generator/configs/
 * 2. Run: bun run dev compile configs/addon.yaml
 * 3. File này sẽ được regenerate tự động
 */

/**
 * Generated ore data
 */
export const GENERATED_ORES = [
  {
    blockId: "apeirix:tin_ore",
    dropItem: "apeirix:raw_tin",
    dropCount: 1,
    fortuneEnabled: true
  },
  {
    blockId: "apeirix:deepslate_tin_ore",
    dropItem: "apeirix:raw_tin",
    dropCount: 1,
    fortuneEnabled: true
  }
];

/**
 * Generated tool data
 */
export const GENERATED_TOOLS = [
  {
    id: "apeirix:bronze_pickaxe",
    type: "pickaxe" as const,
    durability: 375
  },
  {
    id: "apeirix:bronze_axe",
    type: "axe" as const,
    durability: 375
  },
  {
    id: "apeirix:bronze_shovel",
    type: "shovel" as const,
    durability: 375
  },
  {
    id: "apeirix:bronze_hoe",
    type: "hoe" as const,
    durability: 375
  },
  {
    id: "apeirix:bronze_sword",
    type: "sword" as const,
    durability: 375
  },
  {
    id: "apeirix:bronze_spear",
    type: "spear" as const,
    durability: 375
  },
  {
    id: "apeirix:steel_alloy_pickaxe",
    type: "pickaxe" as const,
    durability: 750
  },
  {
    id: "apeirix:steel_alloy_axe",
    type: "axe" as const,
    durability: 750
  },
  {
    id: "apeirix:steel_alloy_shovel",
    type: "shovel" as const,
    durability: 750
  },
  {
    id: "apeirix:steel_alloy_hoe",
    type: "hoe" as const,
    durability: 750
  },
  {
    id: "apeirix:steel_alloy_sword",
    type: "sword" as const,
    durability: 750
  },
  {
    id: "apeirix:wooden_hammer",
    type: "hammer" as const,
    durability: 59
  },
  {
    id: "apeirix:stone_hammer",
    type: "hammer" as const,
    durability: 131
  },
  {
    id: "apeirix:copper_hammer",
    type: "hammer" as const,
    durability: 200
  },
  {
    id: "apeirix:iron_hammer",
    type: "hammer" as const,
    durability: 250
  },
  {
    id: "apeirix:golden_hammer",
    type: "hammer" as const,
    durability: 32
  },
  {
    id: "apeirix:bronze_hammer",
    type: "hammer" as const,
    durability: 375
  },
  {
    id: "apeirix:steel_alloy_hammer",
    type: "hammer" as const,
    durability: 750
  },
  {
    id: "apeirix:diamond_hammer",
    type: "hammer" as const,
    durability: 1561
  },
  {
    id: "apeirix:netherite_hammer",
    type: "hammer" as const,
    durability: 2031
  }
];

/**
 * Generated food data
 */
export const GENERATED_FOODS = [
  {
    itemId: "apeirix:canned_pumpkin",
    effects: [
      { name: "fire_resistance", duration: 15 * 20, amplifier: 0, chance: 1 }
    ],
  },
  {
    itemId: "apeirix:cannedcarrots",
    effects: [
      { name: "night_vision", duration: 15 * 20, amplifier: 0, chance: 1 }
    ],
  },
  {
    itemId: "apeirix:canneddogfood",
    effects: [
      { name: "nausea", duration: 10 * 20, amplifier: 0, chance: 1 }
    ],
  },
  {
    itemId: "apeirix:cannedfish",
    effects: [
      { name: "water_breathing", duration: 30 * 20, amplifier: 0, chance: 1 }
    ],
  },
  {
    itemId: "apeirix:cannedmeal",
    effects: [
      { name: "regeneration", duration: 3 * 20, amplifier: 0, chance: 1 }
    ],
  },
  {
    itemId: "apeirix:cannedsalad",
    effects: [
      { name: "health_boost", duration: 10 * 20, amplifier: 0, chance: 1 }
    ],
  },
  {
    itemId: "apeirix:luncheonmeat",
    effects: [
      { name: "saturation", duration: 1 * 20, amplifier: 0, chance: 1 }
    ],
  },
  {
    itemId: "apeirix:fruit_salad",
    effects: [
      { name: "speed", duration: 20 * 20, amplifier: 0, chance: 1 }
    ],
  },
  {
    itemId: "apeirix:chickensoup",
    effects: [
      { name: "regeneration", duration: 10 * 20, amplifier: 0, chance: 1 }
    ],
  },
  {
    itemId: "apeirix:cookies",
    effects: [
      { name: "haste", duration: 15 * 20, amplifier: 0, chance: 1 }
    ],
  }
];

/**
 * Generated wiki item data
 */
export const GENERATED_WIKI_ITEMS = [
  {
    id: "apeirix:bronze_ingot",
    category: "materials",
    name: "Thỏi Đồng Thanh",
    description: "Hợp kim đồng thanh được tạo từ đồng (copper) và thiếc. Bền hơn đồng nguyên chất, dùng để chế tạo công cụ và giáp.",
    info: {
      "Độ hiếm": "Phổ biến",
      "Chế tạo": "3 copper ingot + 1 tin ingot = 4 bronze",
      "Độ bền công cụ": "375",
      "Độ phù phép": "18"
    },
  },
  {
    id: "apeirix:bronze_nugget",
    category: "materials",
    name: "Mảnh Đồng Thanh",
    description: "Mảnh nhỏ của đồng thanh. 9 mảnh tạo thành 1 thỏi đồng thanh.",
    info: {
      "Độ hiếm": "Phổ biến",
      "Nguồn": "Chia nhỏ thỏi đồng thanh",
      "Chế tạo": "1 thỏi = 9 mảnh"
    },
  },
  {
    id: "apeirix:bronze_block",
    category: "materials",
    name: "Khối Đồng Thanh",
    description: "Khối đồng thanh dùng để lưu trữ hoặc trang trí. Có thể chia thành 9 thỏi.",
    info: {
      "Độ hiếm": "Phổ biến",
      "Độ cứng": "16.65",
      "Chế tạo": "9 thỏi đồng thanh",
      "Công cụ": "Cần cuốc đá trở lên"
    },
  },
  {
    id: "apeirix:steel_alloy_ingot",
    category: "materials",
    name: "Thỏi Hợp Kim Thép",
    description: "Hợp kim thép cao cấp được tạo từ sắt và than. Mạnh hơn nhiều so với đồng thanh, dùng để chế tạo công cụ và giáp cao cấp.",
    info: {
      "Độ Hiếm": "Hiếm",
      "Chế Tạo": "Hợp kim từ sắt và than",
      "Độ Bền Công Cụ": "750",
      "Khả Năng Phù Phép": "22"
    },
  },
  {
    id: "apeirix:steel_alloy_nugget",
    category: "materials",
    name: "Mảnh Hợp Kim Thép",
    description: "Mảnh nhỏ của hợp kim thép. 9 mảnh tạo thành 1 thỏi.",
    info: {
      "Độ Hiếm": "Hiếm",
      "Nguồn": "Phân rã thỏi hợp kim thép",
      "Chế Tạo": "1 thỏi = 9 mảnh"
    },
  },
  {
    id: "apeirix:steel_alloy_block",
    category: "materials",
    name: "Khối Hợp Kim Thép",
    description: "Khối hợp kim thép dùng để lưu trữ hoặc trang trí. Có thể phá thành 9 thỏi.",
    info: {
      "Độ Hiếm": "Hiếm",
      "Độ Cứng": "5.0",
      "Chế Tạo": "9 thỏi hợp kim thép",
      "Công Cụ": "Cần cuốc đá trở lên"
    },
  },
  {
    id: "apeirix:steel_alloy_dust",
    category: "materials",
    name: "Bụi Hợp Kim Thép",
    description: "Bụi hợp kim thép nghiền từ quặng. Có thể rửa để lấy bụi tinh khiết.",
    info: {
      "Độ Hiếm": "Hiếm",
      "Nguồn": "Nghiền quặng bằng Ore Crusher",
      "Xử Lý": "Rửa để lấy bụi tinh khiết"
    },
  },
  {
    id: "apeirix:steel_alloy_dust_pure",
    category: "materials",
    name: "Bụi Hợp Kim Thép Tinh Khiết",
    description: "Bụi hợp kim thép đã được rửa sạch. Nung để lấy thỏi hợp kim thép.",
    info: {
      "Độ Hiếm": "Hiếm",
      "Nguồn": "Rửa bụi hợp kim thép",
      "Xử Lý": "Nung trong lò để lấy thỏi"
    },
  },
  {
    id: "apeirix:raw_tin",
    category: "materials",
    name: "Thiếc Thô",
    description: "Thiếc thô được khai thác từ quặng thiếc. Nấu luyện để có thỏi thiếc.",
    info: {
      "Độ hiếm": "Phổ biến",
      "Nguồn": "Khai thác quặng thiếc",
      "Chế tạo": "Nấu trong lò hoặc lò cao"
    },
  },
  {
    id: "apeirix:tin_ingot",
    category: "materials",
    name: "Thỏi Thiếc",
    description: "Thỏi thiếc tinh luyện. Kết hợp với đồng để tạo hợp kim đồng (bronze).",
    info: {
      "Độ hiếm": "Phổ biến",
      "Nguồn": "Nấu quặng thiếc hoặc thiếc thô",
      "Chế tạo": "9 mảnh thiếc hoặc 1 khối thiếc"
    },
  },
  {
    id: "apeirix:tin_nugget",
    category: "materials",
    name: "Mảnh Thiếc",
    description: "Mảnh nhỏ của thiếc. 9 mảnh tạo thành 1 thỏi thiếc.",
    info: {
      "Độ hiếm": "Phổ biến",
      "Nguồn": "Chia nhỏ thỏi thiếc",
      "Chế tạo": "1 thỏi thiếc = 9 mảnh"
    },
  },
  {
    id: "apeirix:tin_block",
    category: "materials",
    name: "Khối Thiếc",
    description: "Khối thiếc dùng để lưu trữ hoặc trang trí. Có thể chia thành 9 thỏi.",
    info: {
      "Độ hiếm": "Phổ biến",
      "Độ cứng": "16.65",
      "Chế tạo": "9 thỏi thiếc",
      "Công cụ": "Cần cuốc đá trở lên"
    },
  },
  {
    id: "apeirix:tin_ore",
    category: "materials",
    name: "Quặng Thiếc",
    description: "Quặng thiếc tìm thấy dưới lòng đất. Khai thác để có thiếc thô.",
    info: {
      "Độ hiếm": "Phổ biến",
      "Độ sâu": "Y: 0 đến 64",
      "Kích thước mạch": "9 khối",
      "Tần suất": "20 mạch/chunk",
      "Công cụ": "Cần cuốc đá trở lên"
    },
  },
  {
    id: "apeirix:deepslate_tin_ore",
    category: "materials",
    name: "Quặng Thiếc Deepslate",
    description: "Biến thể deepslate của quặng thiếc. Cứng hơn nhưng cho cùng lượng thiếc.",
    info: {
      "Độ hiếm": "Phổ biến",
      "Độ sâu": "Y: 0 đến 64",
      "Độ cứng": "14.985",
      "Công cụ": "Cần cuốc đá trở lên"
    },
  },
  {
    id: "apeirix:bronze_pickaxe",
    category: "tools",
    name: "Cuốc Đồng Thanh",
    description: "Cuốc đồng thanh dùng để khai thác đá và quặng. Tương đương với cuốc sắt.",
    info: {
      "Chất liệu": "Đồng Thanh (Bronze)",
      "Độ bền": "375",
      "Sát thương": "+4",
      "Độ phù phép": "18",
      "Chế tạo": "3 thỏi đồng thanh + 2 gậy"
    },
  },
  {
    id: "apeirix:bronze_axe",
    category: "tools",
    name: "Rìu Đồng Thanh",
    description: "Rìu đồng thanh dùng để chặt gỗ. Cũng có thể dùng làm vũ khí.",
    info: {
      "Chất liệu": "Đồng Thanh (Bronze)",
      "Độ bền": "375",
      "Sát thương": "+5",
      "Độ phù phép": "18",
      "Chế tạo": "3 thỏi đồng thanh + 2 gậy"
    },
  },
  {
    id: "apeirix:bronze_shovel",
    category: "tools",
    name: "Xẻng Đồng Thanh",
    description: "Xẻng đồng thanh dùng để đào đất, cát, sỏi và các khối mềm khác.",
    info: {
      "Chất liệu": "Đồng Thanh (Bronze)",
      "Độ bền": "375",
      "Sát thương": "+3",
      "Độ phù phép": "18",
      "Chế tạo": "1 thỏi đồng thanh + 2 gậy"
    },
  },
  {
    id: "apeirix:bronze_hoe",
    category: "tools",
    name: "Cuốc Cày Đồng Thanh",
    description: "Cuốc cày đồng thanh dùng để làm đất trồng trọt và thu hoạch nhanh cây trồng.",
    info: {
      "Chất liệu": "Đồng Thanh (Bronze)",
      "Độ bền": "375",
      "Sát thương": "+4",
      "Độ phù phép": "18",
      "Chế tạo": "2 thỏi đồng thanh + 2 gậy"
    },
  },
  {
    id: "apeirix:bronze_sword",
    category: "tools",
    name: "Kiếm Đồng Thanh",
    description: "Kiếm đồng thanh dùng để chiến đấu. Chặt mạng nhện và tre nhanh hơn.",
    info: {
      "Chất liệu": "Đồng Thanh (Bronze)",
      "Độ bền": "375",
      "Sát thương": "+6",
      "Độ phù phép": "18",
      "Chế tạo": "2 thỏi đồng thanh + 1 gậy"
    },
  },
  {
    id: "apeirix:bronze_spear",
    category: "tools",
    name: "Giáo Đồng Thanh",
    description: "Giáo đồng thanh có thể ném xa để tấn công từ khoảng cách an toàn.",
    info: {
      "Chất liệu": "Đồng Thanh (Bronze)",
      "Độ bền": "375",
      "Sát thương": "+3",
      "Độ phù phép": "18",
      "Chế tạo": "1 thỏi đồng thanh + 2 gậy"
    },
  },
  {
    id: "apeirix:steel_alloy_pickaxe",
    category: "tools",
    name: "Cuốc Hợp Kim Thép",
    description: "Cuốc hợp kim thép để đào đá và quặng. Tương đương với cuốc kim cương.",
    info: {
      "Vật Liệu": "Hợp Kim Thép",
      "Độ Bền": "750",
      "Sát Thương": "+5",
      "Khả Năng Phù Phép": "22",
      "Chế Tạo": "3 thỏi hợp kim thép + 2 que gỗ"
    },
  },
  {
    id: "apeirix:steel_alloy_axe",
    category: "tools",
    name: "Rìu Hợp Kim Thép",
    description: "Rìu hợp kim thép để chặt gỗ. Cũng có thể dùng làm vũ khí.",
    info: {
      "Vật Liệu": "Hợp Kim Thép",
      "Độ Bền": "750",
      "Sát Thương": "+6",
      "Khả Năng Phù Phép": "22",
      "Chế Tạo": "3 thỏi hợp kim thép + 2 que gỗ"
    },
  },
  {
    id: "apeirix:steel_alloy_shovel",
    category: "tools",
    name: "Xẻng Hợp Kim Thép",
    description: "Xẻng hợp kim thép để đào đất, cát, sỏi và các khối mềm khác.",
    info: {
      "Vật Liệu": "Hợp Kim Thép",
      "Độ Bền": "750",
      "Sát Thương": "+4",
      "Khả Năng Phù Phép": "22",
      "Chế Tạo": "1 thỏi hợp kim thép + 2 que gỗ"
    },
  },
  {
    id: "apeirix:steel_alloy_hoe",
    category: "tools",
    name: "Cuốc Hợp Kim Thép",
    description: "Cuốc hợp kim thép để làm đất và thu hoạch cây trồng nhanh chóng.",
    info: {
      "Vật Liệu": "Hợp Kim Thép",
      "Độ Bền": "750",
      "Sát Thương": "+5",
      "Khả Năng Phù Phép": "22",
      "Chế Tạo": "2 thỏi hợp kim thép + 2 que gỗ"
    },
  },
  {
    id: "apeirix:steel_alloy_sword",
    category: "tools",
    name: "Kiếm Hợp Kim Thép",
    description: "Kiếm hợp kim thép để chiến đấu. Chặt mạng nhện và tre nhanh hơn.",
    info: {
      "Vật Liệu": "Hợp Kim Thép",
      "Độ Bền": "750",
      "Sát Thương": "+7",
      "Khả Năng Phù Phép": "22",
      "Chế Tạo": "2 thỏi hợp kim thép + 1 que gỗ"
    },
  },
  {
    id: "apeirix:steel_alloy_hammer",
    category: "tools",
    name: "Búa Hợp Kim Thép",
    description: "Búa hợp kim thép mạnh mẽ để đào vùng 3x3. Hiệu quả cao cho khai thác quy mô lớn.",
    info: {
      "Vật Liệu": "Hợp Kim Thép",
      "Độ Bền": "750",
      "Sát Thương": "+6",
      "Khả Năng Phù Phép": "22",
      "Chế Tạo": "6 thỏi hợp kim thép + 1 que gỗ",
      "Đặc Biệt": "Đào vùng 3x3"
    },
  },
  {
    id: "apeirix:bronze_helmet",
    category: "armor",
    name: "Mũ Đồng Thanh",
    description: "Mũ giáp đồng thanh bảo vệ đầu. Tương đương với mũ sắt.",
    info: {
      "Chất liệu": "Đồng Thanh (Bronze)",
      "Độ bền": "220",
      "Giáp": "+2",
      "Độ phù phép": "18",
      "Chế tạo": "5 thỏi đồng thanh"
    },
  },
  {
    id: "apeirix:bronze_chestplate",
    category: "armor",
    name: "Áo Giáp Đồng Thanh",
    description: "Áo giáp đồng thanh bảo vệ ngực. Cung cấp bảo vệ tốt nhất.",
    info: {
      "Chất liệu": "Đồng Thanh (Bronze)",
      "Độ bền": "320",
      "Giáp": "+5",
      "Độ phù phép": "18",
      "Chế tạo": "8 thỏi đồng thanh"
    },
  },
  {
    id: "apeirix:bronze_leggings",
    category: "armor",
    name: "Quần Giáp Đồng Thanh",
    description: "Quần giáp đồng thanh bảo vệ chân. Bảo vệ tốt thứ hai sau áo giáp.",
    info: {
      "Chất liệu": "Đồng Thanh (Bronze)",
      "Độ bền": "300",
      "Giáp": "+4",
      "Độ phù phép": "18",
      "Chế tạo": "7 thỏi đồng thanh"
    },
  },
  {
    id: "apeirix:bronze_boots",
    category: "armor",
    name: "Giày Giáp Đồng Thanh",
    description: "Giày giáp đồng thanh bảo vệ bàn chân. Giảm sát thương khi rơi.",
    info: {
      "Chất liệu": "Đồng Thanh (Bronze)",
      "Độ bền": "260",
      "Giáp": "+1",
      "Độ phù phép": "18",
      "Chế tạo": "4 thỏi đồng thanh"
    },
  },
  {
    id: "apeirix:steel_alloy_helmet",
    category: "armor",
    name: "Mũ Hợp Kim Thép",
    description: "Mũ hợp kim thép bảo vệ đầu. Tương đương với mũ kim cương.",
    info: {
      "Vật Liệu": "Hợp Kim Thép",
      "Độ Bền": "440",
      "Giáp": "+3",
      "Khả Năng Phù Phép": "22",
      "Chế Tạo": "5 thỏi hợp kim thép"
    },
  },
  {
    id: "apeirix:steel_alloy_chestplate",
    category: "armor",
    name: "Áo Giáp Hợp Kim Thép",
    description: "Áo giáp hợp kim thép bảo vệ thân. Cung cấp khả năng bảo vệ tốt nhất.",
    info: {
      "Vật Liệu": "Hợp Kim Thép",
      "Độ Bền": "640",
      "Giáp": "+8",
      "Khả Năng Phù Phép": "22",
      "Chế Tạo": "8 thỏi hợp kim thép"
    },
  },
  {
    id: "apeirix:steel_alloy_leggings",
    category: "armor",
    name: "Quần Hợp Kim Thép",
    description: "Quần hợp kim thép bảo vệ chân. Khả năng bảo vệ tốt thứ hai sau áo giáp.",
    info: {
      "Vật Liệu": "Hợp Kim Thép",
      "Độ Bền": "600",
      "Giáp": "+6",
      "Khả Năng Phù Phép": "22",
      "Chế Tạo": "7 thỏi hợp kim thép"
    },
  },
  {
    id: "apeirix:steel_alloy_boots",
    category: "armor",
    name: "Giày Hợp Kim Thép",
    description: "Giày hợp kim thép bảo vệ bàn chân. Giảm sát thương rơi.",
    info: {
      "Vật Liệu": "Hợp Kim Thép",
      "Độ Bền": "520",
      "Giáp": "+3",
      "Khả Năng Phù Phép": "22",
      "Chế Tạo": "4 thỏi hợp kim thép"
    },
  },
  {
    id: "apeirix:canempty",
    category: "foods",
    name: "Hộp Rỗng",
    description: "Hộp thiếc rỗng dùng để đóng hộp thức ăn. Có thể chế tạo hoặc rửa hộp bẩn.",
    info: {
      "Loại": "Vật liệu",
      "Chế tạo": "4 thỏi thiếc",
      "Tái chế": "Rửa hộp bẩn với xô nước"
    },
  },
  {
    id: "apeirix:candirty",
    category: "foods",
    name: "Hộp Bẩn",
    description: "Hộp thiếc đã sử dụng. Cần rửa sạch trước khi dùng lại.",
    info: {
      "Loại": "Vật liệu",
      "Nguồn": "Sau khi ăn đồ hộp",
      "Tái chế": "Rửa với xô nước hoặc thả vào nước"
    },
  },
  {
    id: "apeirix:canned_food",
    category: "foods",
    name: "Thức Ăn Đóng Hộp",
    description: "Thức ăn đóng hộp cơ bản. Bổ dưỡng và bảo quản lâu.",
    info: {
      "Dinh dưỡng": "10 (5 thanh)",
      "Độ no": "12.8",
      "Chế tạo": "Hộp rỗng + 2 thịt nấu chín",
      "Sau khi dùng": "Hộp bẩn"
    },
  },
  {
    id: "apeirix:canned_pumpkin",
    category: "foods",
    name: "Bí Ngô Đóng Hộp",
    description: "Bí ngô đóng hộp. Cho hiệu ứng kháng lửa.",
    info: {
      "Dinh dưỡng": "4 (2 thanh)",
      "Độ no": "4.8",
      "Hiệu ứng": "Kháng lửa 15s",
      "Chế tạo": "Hộp rỗng + bí ngô + đường"
    },
  },
  {
    id: "apeirix:cannedbeets",
    category: "foods",
    name: "Súp Củ Cải Đóng Hộp",
    description: "Súp củ cải đường đóng hộp. Bổ dưỡng và bảo quản lâu dài.",
    info: {
      "Dinh dưỡng": "6 (3 thanh)",
      "Độ no": "7.2",
      "Chế tạo": "Hộp rỗng + súp củ cải",
      "Sau khi dùng": "Hộp bẩn"
    },
  },
  {
    id: "apeirix:cannedbread",
    category: "foods",
    name: "Bánh Mì Đóng Hộp",
    description: "Bánh mì đóng hộp. Tiện lợi và bảo quản lâu.",
    info: {
      "Dinh dưỡng": "5 (2.5 thanh)",
      "Độ no": "6",
      "Chế tạo": "Hộp rỗng + bánh mì",
      "Sau khi dùng": "Hộp bẩn"
    },
  },
  {
    id: "apeirix:cannedcarrots",
    category: "foods",
    name: "Cà Rốt Đóng Hộp",
    description: "Cà rốt đóng hộp. Cho hiệu ứng nhìn đêm.",
    info: {
      "Dinh dưỡng": "4 (2 thanh)",
      "Độ no": "4.8",
      "Hiệu ứng": "Nhìn đêm 15s",
      "Chế tạo": "Hộp rỗng + 3 cà rốt"
    },
  },
  {
    id: "apeirix:canneddogfood",
    category: "foods",
    name: "Thức Ăn Chó Đóng Hộp",
    description: "Thức ăn cho chó đóng hộp. Không nên ăn!",
    info: {
      "Dinh dưỡng": "2 (1 thanh)",
      "Độ no": "0.4",
      "Hiệu ứng": "Buồn nôn 10s",
      "Chế tạo": "Hộp rỗng + 2 thịt thối + xương"
    },
  },
  {
    id: "apeirix:cannedfish",
    category: "foods",
    name: "Cá Đóng Hộp",
    description: "Cá đóng hộp. Cho hiệu ứng thở dưới nước.",
    info: {
      "Dinh dưỡng": "5 (2.5 thanh)",
      "Độ no": "6",
      "Hiệu ứng": "Thở dưới nước 30s",
      "Chế tạo": "Hộp rỗng + 2 cá nấu chín"
    },
  },
  {
    id: "apeirix:cannedmeal",
    category: "foods",
    name: "Bữa Ăn Đóng Hộp",
    description: "Bữa ăn đầy đủ đóng hộp. Cho hiệu ứng hồi máu.",
    info: {
      "Dinh dưỡng": "12 (6 thanh)",
      "Độ no": "16",
      "Hiệu ứng": "Hồi máu II 5s",
      "Chế tạo": "Hộp rỗng + bánh mì + thịt bò + cà rốt"
    },
  },
  {
    id: "apeirix:cannedmushroomsoup",
    category: "foods",
    name: "Súp Nấm Đóng Hộp",
    description: "Súp nấm đóng hộp. Bổ dưỡng và ngon miệng.",
    info: {
      "Dinh dưỡng": "6 (3 thanh)",
      "Độ no": "7.2",
      "Chế tạo": "Hộp rỗng + súp nấm",
      "Sau khi dùng": "Hộp bẩn"
    },
  },
  {
    id: "apeirix:cannedsalad",
    category: "foods",
    name: "Salad Đóng Hộp",
    description: "Salad đóng hộp. Loại bỏ tất cả hiệu ứng.",
    info: {
      "Dinh dưỡng": "3 (1.5 thanh)",
      "Độ no": "3.6",
      "Đặc biệt": "Xóa tất cả hiệu ứng",
      "Chế tạo": "Hộp rỗng + táo + dâu + lá sồi"
    },
  },
  {
    id: "apeirix:luncheonmeat",
    category: "foods",
    name: "Thịt Nguội Đóng Hộp",
    description: "Thịt nguội đóng hộp. Cho hiệu ứng no lâu.",
    info: {
      "Dinh dưỡng": "8 (4 thanh)",
      "Độ no": "10.4",
      "Hiệu ứng": "No lâu 10s",
      "Chế tạo": "Hộp rỗng + thịt lợn + thịt gà"
    },
  },
  {
    id: "apeirix:fruit_salad",
    category: "foods",
    name: "Salad Trái Cây Đóng Hộp",
    description: "Salad trái cây đóng hộp. Cho hiệu ứng tăng tốc.",
    info: {
      "Dinh dưỡng": "6 (3 thanh)",
      "Độ no": "7.2",
      "Hiệu ứng": "Tăng tốc 20s",
      "Chế tạo": "Hộp rỗng + táo + dưa + dâu"
    },
  },
  {
    id: "apeirix:chickensoup",
    category: "foods",
    name: "Súp Gà Đóng Hộp",
    description: "Súp gà đóng hộp. Cho hiệu ứng hồi máu.",
    info: {
      "Dinh dưỡng": "7 (3.5 thanh)",
      "Độ no": "8.4",
      "Hiệu ứng": "Hồi máu 10s",
      "Chế tạo": "Hộp rỗng + thịt gà + cà rốt + khoai tây"
    },
  },
  {
    id: "apeirix:cookies",
    category: "foods",
    name: "Bánh Quy Đóng Hộp",
    description: "Bánh quy đóng hộp. Cho hiệu ứng đào nhanh.",
    info: {
      "Dinh dưỡng": "4 (2 thanh)",
      "Độ no": "4.8",
      "Hiệu ứng": "Đào nhanh 15s",
      "Chế tạo": "Hộp rỗng + 3 bánh quy"
    },
  },
  {
    id: "apeirix:achievement_book",
    category: "special",
    name: "Sổ Thành Tựu",
    description: "Cuốn sổ ghi chép các thành tựu của bạn trong APEIRIX. Sử dụng để xem tiến trình và mở khóa phần thưởng.",
    info: {
      "Loại": "Đặc biệt",
      "Chức năng": "Xem thành tựu",
      "Xếp chồng": "1",
      "Độ hiếm": "Độc nhất"
    },
  },
  {
    id: "apeirix:wiki_book",
    category: "special",
    name: "Bách Khoa Toàn Thư",
    description: "Cuốn sách chứa thông tin về tất cả vật phẩm trong APEIRIX. Sử dụng để tìm hiểu về các vật phẩm trong túi đồ.",
    info: {
      "Loại": "Đặc biệt",
      "Chức năng": "Xem thông tin vật phẩm",
      "Xếp chồng": "1",
      "Độ hiếm": "Độc nhất"
    },
  }
];

/**
 * Generated hammer mining data
 */
export const GENERATED_HAMMER_MINING = [
  {
    blockId: "minecraft:stone",
    stoneDust: "apeirix:cobblestone_dust",
    stoneDustCount: 4
  },
  {
    blockId: "minecraft:cobblestone",
    stoneDust: "apeirix:cobblestone_dust",
    stoneDustCount: 4
  },
  {
    blockId: "minecraft:deepslate",
    stoneDust: "apeirix:deepslate_dust",
    stoneDustCount: 4
  },
  {
    blockId: "minecraft:cobbled_deepslate",
    stoneDust: "apeirix:deepslate_dust",
    stoneDustCount: 4
  },
  {
    blockId: "minecraft:netherrack",
    stoneDust: "apeirix:netherrack_dust",
    stoneDustCount: 4
  },
  {
    blockId: "minecraft:coal_ore",
    stoneDust: "apeirix:cobblestone_dust",
    stoneDustCount: 4,
    oreDust: "apeirix:coal_dust",
    oreDustCount: 9
  },
  {
    blockId: "minecraft:deepslate_coal_ore",
    stoneDust: "apeirix:deepslate_dust",
    stoneDustCount: 4,
    oreDust: "apeirix:coal_dust",
    oreDustCount: 9
  },
  {
    blockId: "minecraft:iron_ore",
    stoneDust: "apeirix:cobblestone_dust",
    stoneDustCount: 4,
    oreDust: "apeirix:iron_ingot_dust",
    oreDustCount: 9
  },
  {
    blockId: "minecraft:deepslate_iron_ore",
    stoneDust: "apeirix:deepslate_dust",
    stoneDustCount: 4,
    oreDust: "apeirix:iron_ingot_dust",
    oreDustCount: 9
  },
  {
    blockId: "minecraft:copper_ore",
    stoneDust: "apeirix:cobblestone_dust",
    stoneDustCount: 4,
    oreDust: "apeirix:copper_ingot_dust",
    oreDustCount: 9
  },
  {
    blockId: "minecraft:deepslate_copper_ore",
    stoneDust: "apeirix:deepslate_dust",
    stoneDustCount: 4,
    oreDust: "apeirix:copper_ingot_dust",
    oreDustCount: 9
  },
  {
    blockId: "minecraft:gold_ore",
    stoneDust: "apeirix:cobblestone_dust",
    stoneDustCount: 4,
    oreDust: "apeirix:gold_ingot_dust",
    oreDustCount: 9
  },
  {
    blockId: "minecraft:deepslate_gold_ore",
    stoneDust: "apeirix:deepslate_dust",
    stoneDustCount: 4,
    oreDust: "apeirix:gold_ingot_dust",
    oreDustCount: 9
  },
  {
    blockId: "minecraft:diamond_ore",
    stoneDust: "apeirix:cobblestone_dust",
    stoneDustCount: 4,
    oreDust: "apeirix:diamond_dust",
    oreDustCount: 9
  },
  {
    blockId: "minecraft:deepslate_diamond_ore",
    stoneDust: "apeirix:deepslate_dust",
    stoneDustCount: 4,
    oreDust: "apeirix:diamond_dust",
    oreDustCount: 9
  },
  {
    blockId: "minecraft:emerald_ore",
    stoneDust: "apeirix:cobblestone_dust",
    stoneDustCount: 4,
    oreDust: "apeirix:emerald_dust",
    oreDustCount: 9
  },
  {
    blockId: "minecraft:deepslate_emerald_ore",
    stoneDust: "apeirix:deepslate_dust",
    stoneDustCount: 4,
    oreDust: "apeirix:emerald_dust",
    oreDustCount: 9
  },
  {
    blockId: "minecraft:lapis_ore",
    stoneDust: "apeirix:cobblestone_dust",
    stoneDustCount: 4,
    oreDust: "apeirix:lapis_block_dust",
    oreDustCount: 9
  },
  {
    blockId: "minecraft:deepslate_lapis_ore",
    stoneDust: "apeirix:deepslate_dust",
    stoneDustCount: 4,
    oreDust: "apeirix:lapis_block_dust",
    oreDustCount: 9
  },
  {
    blockId: "minecraft:redstone_ore",
    stoneDust: "apeirix:cobblestone_dust",
    stoneDustCount: 4
  },
  {
    blockId: "minecraft:deepslate_redstone_ore",
    stoneDust: "apeirix:deepslate_dust",
    stoneDustCount: 4
  },
  {
    blockId: "apeirix:tin_ore",
    stoneDust: "apeirix:cobblestone_dust",
    stoneDustCount: 4,
    oreDust: "apeirix:tin_ingot_dust",
    oreDustCount: 9
  },
  {
    blockId: "apeirix:deepslate_tin_ore",
    stoneDust: "apeirix:deepslate_dust",
    stoneDustCount: 4,
    oreDust: "apeirix:tin_ingot_dust",
    oreDustCount: 9
  }
];

/**
 * Generated hammer tool IDs
 */
export const GENERATED_HAMMER_IDS = [
  "apeirix:wooden_hammer",
  "apeirix:stone_hammer",
  "apeirix:copper_hammer",
  "apeirix:iron_hammer",
  "apeirix:golden_hammer",
  "apeirix:bronze_hammer",
  "apeirix:steel_alloy_hammer",
  "apeirix:diamond_hammer",
  "apeirix:netherite_hammer"
];

/**
 * Generated brass sifter recipes
 */
export const GENERATED_BRASS_SIFTER = [
  {
    dustId: "apeirix:bronze_ingot_dust",
    pureDustId: "apeirix:bronze_ingot_dust_pure",
    stoneDustId: "apeirix:cobblestone_dust"
  },
  {
    dustId: "apeirix:steel_alloy_dust",
    pureDustId: "apeirix:steel_alloy_dust_pure",
    stoneDustId: "apeirix:cobblestone_dust"
  },
  {
    dustId: "apeirix:coal_dust",
    pureDustId: "apeirix:coal_dust_pure",
    stoneDustId: "apeirix:cobblestone_dust"
  },
  {
    dustId: "apeirix:copper_ingot_dust",
    pureDustId: "apeirix:copper_ingot_dust_pure",
    stoneDustId: "apeirix:cobblestone_dust"
  },
  {
    dustId: "apeirix:iron_ingot_dust",
    pureDustId: "apeirix:iron_ingot_dust_pure",
    stoneDustId: "apeirix:cobblestone_dust"
  },
  {
    dustId: "apeirix:gold_ingot_dust",
    pureDustId: "apeirix:gold_ingot_dust_pure",
    stoneDustId: "apeirix:cobblestone_dust"
  },
  {
    dustId: "apeirix:tin_ingot_dust",
    pureDustId: "apeirix:tin_ingot_dust_pure",
    stoneDustId: "apeirix:cobblestone_dust"
  },
  {
    dustId: "apeirix:diamond_dust",
    pureDustId: "apeirix:diamond_dust_pure",
    stoneDustId: "apeirix:cobblestone_dust"
  },
  {
    dustId: "apeirix:emerald_dust",
    pureDustId: "apeirix:emerald_dust_pure",
    stoneDustId: "apeirix:cobblestone_dust"
  },
  {
    dustId: "apeirix:lapis_block_dust",
    pureDustId: "apeirix:lapis_block_dust_pure",
    stoneDustId: "apeirix:cobblestone_dust"
  }
];

/**
 * Generated Rust Mite edible items
 * Auto-generated from all foods and raw ores
 */
export const GENERATED_RUST_MITE_EDIBLE_ITEMS = [
  "apeirix:bronze_ingot_dust",
  "apeirix:bronze_ingot_dust_pure",
  "apeirix:candirty",
  "apeirix:canempty",
  "apeirix:canned_pumpkin",
  "apeirix:cannedcarrots",
  "apeirix:canneddogfood",
  "apeirix:cannedfish",
  "apeirix:cannedmeal",
  "apeirix:cannedsalad",
  "apeirix:chickensoup",
  "apeirix:coal_dust",
  "apeirix:coal_dust_pure",
  "apeirix:cobblestone_dust",
  "apeirix:cookies",
  "apeirix:copper_ingot_dust",
  "apeirix:copper_ingot_dust_pure",
  "apeirix:deepslate_dust",
  "apeirix:diamond_dust",
  "apeirix:diamond_dust_pure",
  "apeirix:emerald_dust",
  "apeirix:emerald_dust_pure",
  "apeirix:fruit_salad",
  "apeirix:gold_ingot_dust",
  "apeirix:gold_ingot_dust_pure",
  "apeirix:iron_ingot_dust",
  "apeirix:iron_ingot_dust_pure",
  "apeirix:lapis_block_dust",
  "apeirix:lapis_block_dust_pure",
  "apeirix:luncheonmeat",
  "apeirix:netherrack_dust",
  "apeirix:raw_tin",
  "apeirix:redstone_dust_pure",
  "apeirix:steel_alloy_dust",
  "apeirix:steel_alloy_dust_pure",
  "apeirix:tin_ingot_dust",
  "apeirix:tin_ingot_dust_pure",
  "minecraft:raw_copper",
  "minecraft:raw_gold",
  "minecraft:raw_iron"
];
