import { FileManager } from '../core/FileManager.js';
import { join } from 'path';
import { Logger } from '../utils/Logger.js';

export interface AttributeMapping {
  [attributeId: string]: string[]; // attributeId -> itemIds[]
}

/**
 * Generator để tạo file GeneratedAttributes.ts
 * 
 * Đọc tất cả YAML configs và extract field `attributes` từ:
 * - Materials (items, ores, blocks)
 * - Tools (pickaxe, axe, sword, hammer, etc.)
 * - Armor (helmet, chestplate, leggings, boots)
 * - Foods
 * - Entities
 * - Special items
 */
export class AttributeGenerator {
  private projectRoot: string;

  constructor(projectRoot: string) {
    this.projectRoot = projectRoot;
  }

  /**
   * Generate GeneratedAttributes.ts file
   */
  generate(attributeMapping: AttributeMapping, customPath?: string): void {
    const content = this.generateContent(attributeMapping);
    
    const outputPath = customPath 
      ? join(this.projectRoot, customPath, 'GeneratedAttributes.ts')
      : join(this.projectRoot, 'scripts/data/GeneratedAttributes.ts');
    
    FileManager.writeText(outputPath, content);
    
    const displayPath = customPath 
      ? `${customPath}/GeneratedAttributes.ts`
      : 'scripts/data/GeneratedAttributes.ts';
    Logger.log(`✅ Đã tạo: ${displayPath}`);
  }

  /**
   * Generate file content
   */
  private generateContent(attributeMapping: AttributeMapping): string {
    // Sort attributes alphabetically
    const sortedAttributes = Object.keys(attributeMapping).sort();
    
    // Generate attribute constants
    const attributeConstants = sortedAttributes.map(attrId => {
      const itemIds = attributeMapping[attrId];
      const itemsStr = itemIds.map(id => `  '${id}'`).join(',\n');
      return `  '${attrId}': [\n${itemsStr}\n  ]`;
    }).join(',\n');

    // Count total items with attributes
    const totalItems = Object.values(attributeMapping).reduce((sum, items) => sum + items.length, 0);

    return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by addon-generator CLI
 * 
 * Để thêm/sửa/xóa attributes:
 * 1. Edit field 'attributes' trong YAML files (configs/materials/, configs/tools/, etc.)
 * 2. Run: bun run dev compile configs/addon.yaml
 * 3. File này sẽ được regenerate tự động
 * 
 * Generated: ${new Date().toISOString()}
 * Total attributes: ${sortedAttributes.length}
 * Total items with attributes: ${totalItems}
 */

/**
 * Attribute mapping: attributeId -> itemIds[]
 * 
 * Usage:
 * - Check if item has attribute: GENERATED_ATTRIBUTES['hammer_mining'].includes(itemId)
 * - Get all items with attribute: GENERATED_ATTRIBUTES['rust_mite_edible']
 */
export const GENERATED_ATTRIBUTES: Record<string, string[]> = {
${attributeConstants}
};

/**
 * Helper: Check if item has specific attribute
 */
export function hasAttribute(itemId: string, attributeId: string): boolean {
  const items = GENERATED_ATTRIBUTES[attributeId];
  return items ? items.includes(itemId) : false;
}

/**
 * Helper: Get all attributes for an item
 */
export function getItemAttributes(itemId: string): string[] {
  const attributes: string[] = [];
  for (const [attrId, itemIds] of Object.entries(GENERATED_ATTRIBUTES)) {
    if (itemIds.includes(itemId)) {
      attributes.push(attrId);
    }
  }
  return attributes;
}

/**
 * Helper: Get all items with specific attribute
 */
export function getItemsWithAttribute(attributeId: string): string[] {
  return GENERATED_ATTRIBUTES[attributeId] || [];
}
`;
  }
}
