import { FileManager } from '../core/FileManager.js';
import { join } from 'path';
import { Logger } from '../utils/Logger.js';

// Attribute data for each item
export interface AttributeItemData {
  itemId: string;
  config?: any; // Optional config object (e.g., {damageMultiplier: 1.5})
}

// Mapping: attributeId -> array of items with that attribute
export interface AttributeMapping {
  [attributeId: string]: AttributeItemData[];
}

/**
 * Generator để tạo file GeneratedAttributes.ts
 * 
 * Đọc tất cả YAML configs và extract field `attributes` từ:
 * - Materials (items, ores, blocks)
 * - Tools (pickaxe, axe, sword, hammer, etc.)
 * - Armor (helmet, chestplate, leggings, boots)
 * - Foods
 * - Entities
 * - Special items
 */
export class AttributeGenerator {
  private projectRoot: string;

  constructor(projectRoot: string) {
    this.projectRoot = projectRoot;
  }

  /**
   * Generate GeneratedAttributes.ts file
   */
  generate(attributeMapping: AttributeMapping, customPath?: string): void {
    const content = this.generateContent(attributeMapping);
    
    const outputPath = customPath 
      ? join(this.projectRoot, customPath, 'GeneratedAttributes.ts')
      : join(this.projectRoot, 'scripts/data/GeneratedAttributes.ts');
    
    FileManager.writeText(outputPath, content);
    
    const displayPath = customPath 
      ? `${customPath}/GeneratedAttributes.ts`
      : 'scripts/data/GeneratedAttributes.ts';
    Logger.log(`✅ Đã tạo: ${displayPath}`);
  }

  /**
   * Generate file content
   */
  private generateContent(attributeMapping: AttributeMapping): string {
    // Sort attributes alphabetically
    const sortedAttributes = Object.keys(attributeMapping).sort();
    
    // Generate attribute constants
    const attributeConstants = sortedAttributes.map(attrId => {
      const items = attributeMapping[attrId];
      const itemsStr = items.map(item => {
        if (item.config) {
          // Has config - output as object
          const configStr = JSON.stringify(item.config);
          return `    { itemId: '${item.itemId}', config: ${configStr} }`;
        } else {
          // No config - output as simple object
          return `    { itemId: '${item.itemId}' }`;
        }
      }).join(',\n');
      return `  '${attrId}': [\n${itemsStr}\n  ]`;
    }).join(',\n');

    // Count total items with attributes
    const totalItems = Object.values(attributeMapping).reduce((sum, items) => sum + items.length, 0);

    return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by addon-generator CLI
 * 
 * Để thêm/sửa/xóa attributes:
 * 1. Edit field 'attributes' trong YAML files (configs/materials/, configs/tools/, etc.)
 * 2. Run: bun run dev compile configs/addon.yaml
 * 3. File này sẽ được regenerate tự động
 * 
 * Generated: ${new Date().toISOString()}
 * Total attributes: ${sortedAttributes.length}
 * Total items with attributes: ${totalItems}
 */

// Attribute data for each item
export interface AttributeItemData {
  itemId: string;
  config?: any; // Optional config object
}

/**
 * Attribute mapping: attributeId -> array of items with config
 * 
 * Usage:
 * - Check if item has attribute: hasAttribute(itemId, 'hammer_mining')
 * - Get all items with attribute: getItemsWithAttribute('rust_mite_edible')
 * - Get attribute config: getAttributeConfig(itemId, 'undead_slayer')
 */
export const GENERATED_ATTRIBUTES: Record<string, AttributeItemData[]> = {
${attributeConstants}
};

/**
 * Helper: Check if item has specific attribute
 */
export function hasAttribute(itemId: string, attributeId: string): boolean {
  const items = GENERATED_ATTRIBUTES[attributeId];
  return items ? items.some(item => item.itemId === itemId) : false;
}

/**
 * Helper: Get all attributes for an item
 */
export function getItemAttributes(itemId: string): string[] {
  const attributes: string[] = [];
  for (const [attrId, items] of Object.entries(GENERATED_ATTRIBUTES)) {
    if (items.some(item => item.itemId === itemId)) {
      attributes.push(attrId);
    }
  }
  return attributes;
}

/**
 * Helper: Get all items with specific attribute (returns itemIds only)
 */
export function getItemsWithAttribute(attributeId: string): string[] {
  const items = GENERATED_ATTRIBUTES[attributeId] || [];
  return items.map(item => item.itemId);
}

/**
 * Helper: Get attribute config for specific item
 */
export function getAttributeConfig(itemId: string, attributeId: string): any | undefined {
  const items = GENERATED_ATTRIBUTES[attributeId];
  if (!items) return undefined;
  
  const itemData = items.find(item => item.itemId === itemId);
  return itemData?.config;
}

/**
 * Helper: Get all items with attribute including config
 */
export function getAttributeItems(attributeId: string): AttributeItemData[] {
  return GENERATED_ATTRIBUTES[attributeId] || [];
}
`;
  }
}
