import { FileManager } from '../core/FileManager.js';
import { join } from 'path';

export interface ToolData {
  id: string;
  type: string;
  durability: number;
}

export interface FoodData {
  id: string;
  effects?: Array<{
    name: string;
    duration: number;
    amplifier: number;
    chance?: number;
  }>;
  removeEffects?: boolean;
}

export interface OreData {
  blockId: string;
  dropItem: string;
  dropCount: number;
  fortuneEnabled: boolean;
}

export interface WikiItemData {
  id: string;
  category: string;
  name?: string;
  description?: string;
  icon?: string;
  info?: Record<string, string | number | boolean>;
}

export interface HammerMiningData {
  blockId: string;
  stoneDust: string;
  stoneDustCount: number;
  oreDust?: string;
  oreDustCount?: number;
}

export interface BrassSifterData {
  dustId: string;
  pureDustId: string;
  stoneDustId: string;
}

/**
 * Generator để tạo file GeneratedGameData.ts
 * File này chứa tất cả tools, foods, ores được generate từ CLI
 */
export class GameDataGenerator {
  private projectRoot: string;

  constructor(projectRoot: string) {
    this.projectRoot = projectRoot;
  }

  /**
   * Generate GeneratedGameData.ts file
   * @param tools Tool data array
   * @param foods Food data array
   * @param ores Ore data array
   * @param wikiItems Wiki item data array
   * @param hammerMining Hammer mining data array
   * @param brassSifter Brass sifter data array
   * @param customPath Optional custom output path (relative to projectRoot)
   */
  generate(tools: ToolData[], foods: FoodData[], ores: OreData[], wikiItems: WikiItemData[], hammerMining: HammerMiningData[], brassSifter: BrassSifterData[], customPath?: string): void {
    const content = this.generateContent(tools, foods, ores, wikiItems, hammerMining, brassSifter);
    // Output to specified path or default to root scripts/data folder
    const outputPath = customPath 
      ? join(this.projectRoot, customPath, 'GeneratedGameData.ts')
      : join(this.projectRoot, 'scripts/data/GeneratedGameData.ts');
    
    FileManager.writeText(outputPath, content);
    
    const displayPath = customPath 
      ? `${customPath}/GeneratedGameData.ts`
      : 'scripts/data/GeneratedGameData.ts';
    console.log(`✅ Đã tạo: ${displayPath}`);
  }

  /**
   * Generate file content
   */
  private generateContent(tools: ToolData[], foods: FoodData[], ores: OreData[], wikiItems: WikiItemData[], hammerMining: HammerMiningData[], brassSifter: BrassSifterData[]): string {
    return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by addon-generator CLI
 * 
 * Để thêm/sửa/xóa content:
 * 1. Edit YAML files trong addon-generator/configs/
 * 2. Run: bun run dev compile configs/addon.yaml
 * 3. File này sẽ được regenerate tự động
 */

/**
 * Generated ore data
 */
export const GENERATED_ORES = [
${this.generateOreData(ores)}
];

/**
 * Generated tool data
 */
export const GENERATED_TOOLS = [
${this.generateToolData(tools)}
];

/**
 * Generated food data
 */
export const GENERATED_FOODS = [
${this.generateFoodData(foods)}
];

/**
 * Generated wiki item data
 */
export const GENERATED_WIKI_ITEMS = [
${this.generateWikiData(wikiItems)}
];

/**
 * Generated hammer mining data
 */
export const GENERATED_HAMMER_MINING = [
${this.generateHammerMiningData(hammerMining)}
];

/**
 * Generated hammer tool IDs
 */
export const GENERATED_HAMMER_IDS = [
${this.generateHammerIds(tools)}
];

/**
 * Generated brass sifter recipes
 */
export const GENERATED_BRASS_SIFTER = [
${this.generateBrassSifterData(brassSifter)}
];
`;
  }

  /**
   * Generate ore data
   */
  private generateOreData(ores: OreData[]): string {
    if (ores.length === 0) {
      return '  // No ores generated';
    }

    return ores.map(ore => {
      return `  {
    blockId: "${ore.blockId}",
    dropItem: "${ore.dropItem}",
    dropCount: ${ore.dropCount},
    fortuneEnabled: ${ore.fortuneEnabled}
  }`;
    }).join(',\n');
  }

  /**
   * Generate tool data
   */
  private generateToolData(tools: ToolData[]): string {
    if (tools.length === 0) {
      return '  // No tools generated';
    }

    return tools.map(tool => {
      return `  {
    id: "${tool.id}",
    type: "${tool.type}" as const,
    durability: ${tool.durability}
  }`;
    }).join(',\n');
  }

  /**
   * Generate food data
   */
  private generateFoodData(foods: FoodData[]): string {
    if (foods.length === 0) {
      return '  // No foods with effects generated';
    }

    return foods.map(food => {
      const lines: string[] = [];
      lines.push(`  {`);
      lines.push(`    itemId: "${food.id}",`);

      if (food.effects && food.effects.length > 0) {
        lines.push(`    effects: [`);
        food.effects.forEach((effect, index) => {
          const isLast = index === food.effects!.length - 1;
          const chance = effect.chance !== undefined ? `, chance: ${effect.chance}` : '';
          lines.push(`      { name: "${effect.name}", duration: ${effect.duration} * 20, amplifier: ${effect.amplifier}${chance} }${isLast ? '' : ','}`);
        });
        lines.push(`    ],`);
      }

      if (food.removeEffects) {
        lines.push(`    removeEffects: true,`);
      }

      lines.push(`  }`);
      return lines.join('\n');
    }).join(',\n');
  }

  /**
   * Generate wiki data
   */
  private generateWikiData(wikiItems: WikiItemData[]): string {
    if (wikiItems.length === 0) {
      return '  // No wiki items generated';
    }

    return wikiItems.map(item => {
      const lines: string[] = [];
      lines.push(`  {`);
      lines.push(`    id: "${item.id}",`);
      lines.push(`    category: "${item.category}",`);
      
      if (item.name) {
        lines.push(`    name: "${item.name}",`);
      }
      
      if (item.description) {
        lines.push(`    description: "${item.description}",`);
      }
      
      if (item.icon) {
        lines.push(`    icon: "${item.icon}",`);
      }
      
      if (item.info && Object.keys(item.info).length > 0) {
        lines.push(`    info: {`);
        const infoEntries = Object.entries(item.info);
        infoEntries.forEach(([key, value], index) => {
          const isLast = index === infoEntries.length - 1;
          const formattedValue = typeof value === 'string' ? `"${value}"` : value;
          // Quote key nếu có dấu cách hoặc ký tự đặc biệt
          const quotedKey = /[^a-zA-Z0-9_$]/.test(key) ? `"${key}"` : key;
          lines.push(`      ${quotedKey}: ${formattedValue}${isLast ? '' : ','}`);
        });
        lines.push(`    },`);
      }
      
      lines.push(`  }`);
      return lines.join('\n');
    }).join(',\n');
  }

  /**
   * Generate hammer mining data
   */
  private generateHammerMiningData(hammerMining: HammerMiningData[]): string {
    if (hammerMining.length === 0) {
      return '  // No hammer mining data generated';
    }

    return hammerMining.map(block => {
      const lines: string[] = [];
      lines.push(`  {`);
      lines.push(`    blockId: "${block.blockId}",`);
      lines.push(`    stoneDust: "${block.stoneDust}",`);
      
      if (block.oreDust && block.oreDustCount) {
        lines.push(`    stoneDustCount: ${block.stoneDustCount},`);
        lines.push(`    oreDust: "${block.oreDust}",`);
        lines.push(`    oreDustCount: ${block.oreDustCount}`);
      } else {
        lines.push(`    stoneDustCount: ${block.stoneDustCount}`);
      }
      
      lines.push(`  }`);
      return lines.join('\n');
    }).join(',\n');
  }

  /**
   * Generate hammer IDs from tools
   */
  private generateHammerIds(tools: ToolData[]): string {
    const hammers = tools.filter(tool => tool.type === 'hammer');
    
    if (hammers.length === 0) {
      return '  // No hammers generated';
    }

    return hammers.map(hammer => `  "${hammer.id}"`).join(',\n');
  }

  /**
   * Generate brass sifter data
   */
  private generateBrassSifterData(brassSifter: BrassSifterData[]): string {
    if (brassSifter.length === 0) {
      return '  // No brass sifter recipes generated';
    }

    return brassSifter.map(recipe => {
      return `  {
    dustId: "${recipe.dustId}",
    pureDustId: "${recipe.pureDustId}",
    stoneDustId: "${recipe.stoneDustId}"
  }`;
    }).join(',\n');
  }
}
