import { FileManager } from '../core/FileManager.js';
import { join } from 'path';

export interface ToolData {
  id: string;
  type: string;
  durability: number;
}

export interface FoodData {
  id: string;
  effects?: Array<{
    name: string;
    duration: number;
    amplifier: number;
    chance?: number;
  }>;
  removeEffects?: boolean;
}

export interface OreData {
  blockId: string;
  dropItem: string;
  dropCount: number;
  fortuneEnabled: boolean;
}

/**
 * Generator để tạo file GeneratedGameData.ts
 * File này chứa tất cả tools, foods, ores được generate từ CLI
 */
export class GameDataGenerator {
  private projectRoot: string;

  constructor(projectRoot: string) {
    this.projectRoot = projectRoot;
  }

  /**
   * Generate GeneratedGameData.ts file
   */
  generate(tools: ToolData[], foods: FoodData[], ores: OreData[]): void {
    const content = this.generateContent(tools, foods, ores);
    // Output to root scripts/data folder
    const outputPath = join(this.projectRoot, 'scripts/data/GeneratedGameData.ts');
    
    FileManager.writeText(outputPath, content);
    console.log(`✅ Đã tạo: scripts/data/GeneratedGameData.ts`);
  }

  /**
   * Generate file content
   */
  private generateContent(tools: ToolData[], foods: FoodData[], ores: OreData[]): string {
    return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by addon-generator CLI
 * 
 * Để thêm/sửa/xóa content:
 * 1. Edit YAML files trong addon-generator/configs/
 * 2. Run: bun run dev compile configs/addon.yaml
 * 3. File này sẽ được regenerate tự động
 */

/**
 * Generated ore data
 */
export const GENERATED_ORES = [
${this.generateOreData(ores)}
];

/**
 * Generated tool data
 */
export const GENERATED_TOOLS = [
${this.generateToolData(tools)}
];

/**
 * Generated food data
 */
export const GENERATED_FOODS = [
${this.generateFoodData(foods)}
];
`;
  }

  /**
   * Generate ore data
   */
  private generateOreData(ores: OreData[]): string {
    if (ores.length === 0) {
      return '  // No ores generated';
    }

    return ores.map(ore => {
      return `  {
    blockId: "${ore.blockId}",
    dropItem: "${ore.dropItem}",
    dropCount: ${ore.dropCount},
    fortuneEnabled: ${ore.fortuneEnabled}
  }`;
    }).join(',\n');
  }

  /**
   * Generate tool data
   */
  private generateToolData(tools: ToolData[]): string {
    if (tools.length === 0) {
      return '  // No tools generated';
    }

    return tools.map(tool => {
      return `  {
    id: "${tool.id}",
    type: "${tool.type}" as const,
    durability: ${tool.durability}
  }`;
    }).join(',\n');
  }

  /**
   * Generate food data
   */
  private generateFoodData(foods: FoodData[]): string {
    if (foods.length === 0) {
      return '  // No foods with effects generated';
    }

    return foods.map(food => {
      const lines: string[] = [];
      lines.push(`  {`);
      lines.push(`    itemId: "${food.id}",`);

      if (food.effects && food.effects.length > 0) {
        lines.push(`    effects: [`);
        food.effects.forEach((effect, index) => {
          const isLast = index === food.effects!.length - 1;
          const chance = effect.chance !== undefined ? `, chance: ${effect.chance}` : '';
          lines.push(`      { name: "${effect.name}", duration: ${effect.duration} * 20, amplifier: ${effect.amplifier}${chance} }${isLast ? '' : ','}`);
        });
        lines.push(`    ],`);
      }

      if (food.removeEffects) {
        lines.push(`    removeEffects: true,`);
      }

      lines.push(`  }`);
      return lines.join('\n');
    }).join(',\n');
  }
}
