import { FileManager } from '../core/FileManager.js';
import { join } from 'path';

export interface ProcessingRecipeData {
  machineType: string;
  input: string;
  output: string;
  processingTime: number;
}

/**
 * Generator để tạo file GeneratedProcessingRecipes.ts
 */
export class ProcessingRecipeGenerator {
  private projectRoot: string;

  constructor(projectRoot: string) {
    this.projectRoot = projectRoot;
  }

  /**
   * Generate GeneratedProcessingRecipes.ts file
   */
  generate(recipes: ProcessingRecipeData[], customPath?: string): void {
    const content = this.generateContent(recipes);
    
    const outputPath = customPath 
      ? join(this.projectRoot, customPath, 'GeneratedProcessingRecipes.ts')
      : join(this.projectRoot, 'scripts/data/GeneratedProcessingRecipes.ts');
    
    FileManager.writeText(outputPath, content);
    
    const displayPath = customPath 
      ? `${customPath}/GeneratedProcessingRecipes.ts`
      : 'scripts/data/GeneratedProcessingRecipes.ts';
    console.log(`✅ Đã tạo: ${displayPath}`);
  }

  /**
   * Generate file content
   */
  private generateContent(recipes: ProcessingRecipeData[]): string {
    // Group recipes by machine type
    const recipesByMachine: Record<string, ProcessingRecipeData[]> = {};
    
    for (const recipe of recipes) {
      if (!recipesByMachine[recipe.machineType]) {
        recipesByMachine[recipe.machineType] = [];
      }
      recipesByMachine[recipe.machineType].push(recipe);
    }

    return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by addon-generator CLI
 * 
 * Để thêm/sửa/xóa processing recipes:
 * 1. Edit YAML files trong addon-generator/configs/materials/processing/
 * 2. Run: bun run dev compile configs/addon.yaml
 * 3. File này sẽ được regenerate tự động
 */

export interface ProcessingRecipe {
  inputId: string;
  outputId: string;
  processingTime: number;
}

/**
 * Generated processing recipes grouped by machine type
 */
export const GENERATED_PROCESSING_RECIPES: Record<string, ProcessingRecipe[]> = {
${this.generateRecipesByMachine(recipesByMachine)}
};
`;
  }

  /**
   * Generate recipes grouped by machine
   */
  private generateRecipesByMachine(recipesByMachine: Record<string, ProcessingRecipeData[]>): string {
    const lines: string[] = [];
    
    for (const [machineType, recipes] of Object.entries(recipesByMachine)) {
      lines.push(`  "${machineType}": [`);
      
      recipes.forEach((recipe, index) => {
        const isLast = index === recipes.length - 1;
        lines.push(`    { inputId: "${recipe.input}", outputId: "${recipe.output}", processingTime: ${recipe.processingTime} }${isLast ? '' : ','}`);
      });
      
      lines.push(`  ],`);
    }
    
    return lines.join('\n');
  }
}
