type: shovel
id: flint_shovel
name: lang:tools.flint_shovel
lore: lang:lore.auto
wikiDescription: lang:wiki.tools.flint_shovel
texture: ../assets/flint_shovel.png
damage: 1
category: equipment
group: itemGroup.name.shovel
diggerTags:
  - dirt
  - sand
  - gravel
  - grass
  - snow
recipe:
  type: shaped
  id: flint_shovel
  pattern:
    - " #"
    - " S"
  ingredients:
    "#": apeirix:flint_shard
    S: minecraft:stick
  result: apeirix:flint_shovel
  count: 1
  unlock:
    - apeirix:flint_shard
materialId: apeirix:flint_shard
durability: 12
enchantability: 15
tier: wood
attributes:
  durability_modifier:
    durability: 12
  combat_damage_modifier:
    context: combat
    damage: 0.5
  breakable:
    context: mining
    value: 100
    conditions:
      blockTags:
        - ore
        - stone
