# Flint Shard - Mảnh đá lửa từ sỏi
id: flint_shard
name: lang:materials.flint_shard
lore: lang:lore.materials.flint_shard
wikiDescription: lang:wiki.materials.flint_shard
texture: ../assets/special/flint_shard.png
category: items
maxStackSize: 64
recipes:
  - type: shapeless
    id: flint_to_shards
    ingredients:
      - minecraft:flint
    result: apeirix:flint_shard
    count: 2
    unlock:
      - minecraft:flint
